// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: audit_log_entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLogEntry = `-- name: CreateAuditLogEntry :one
INSERT INTO audit_log_entries (actor_id, actor_type, action, target_entity, target_id, before_state, after_state)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, actor_id, actor_type, action, target_entity, target_id, before_state, after_state, created_at
`

type CreateAuditLogEntryParams struct {
	ActorID      pgtype.UUID `json:"actor_id"`
	ActorType    string      `json:"actor_type"`
	Action       string      `json:"action"`
	TargetEntity string      `json:"target_entity"`
	TargetID     pgtype.UUID `json:"target_id"`
	BeforeState  []byte      `json:"before_state"`
	AfterState   []byte      `json:"after_state"`
}

func (q *Queries) CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (AuditLogEntry, error) {
	row := q.db.QueryRow(ctx, createAuditLogEntry,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.TargetEntity,
		arg.TargetID,
		arg.BeforeState,
		arg.AfterState,
	)
	var i AuditLogEntry
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.ActorType,
		&i.Action,
		&i.TargetEntity,
		&i.TargetID,
		&i.BeforeState,
		&i.AfterState,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogEntriesByTarget = `-- name: ListAuditLogEntriesByTarget :many
SELECT id, actor_id, actor_type, action, target_entity, target_id, before_state, after_state, created_at FROM audit_log_entries
WHERE target_entity = $1 AND target_id = $2
ORDER BY created_at DESC
`

type ListAuditLogEntriesByTargetParams struct {
	TargetEntity string      `json:"target_entity"`
	TargetID     pgtype.UUID `json:"target_id"`
}

func (q *Queries) ListAuditLogEntriesByTarget(ctx context.Context, arg ListAuditLogEntriesByTargetParams) ([]AuditLogEntry, error) {
	rows, err := q.db.Query(ctx, listAuditLogEntriesByTarget, arg.TargetEntity, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLogEntry{}
	for rows.Next() {
		var i AuditLogEntry
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.TargetEntity,
			&i.TargetID,
			&i.BeforeState,
			&i.AfterState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
