// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (merchant_id, customer_contact, channel, direction, message_type, template_id, consent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, customer_contact, channel, direction, message_type, template_id, consent, created_at
`

type CreateConversationParams struct {
	MerchantID      pgtype.UUID `json:"merchant_id"`
	CustomerContact string      `json:"customer_contact"`
	Channel         string      `json:"channel"`
	Direction       string      `json:"direction"`
	MessageType     string      `json:"message_type"`
	TemplateID      pgtype.Text `json:"template_id"`
	Consent         bool        `json:"consent"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.MerchantID,
		arg.CustomerContact,
		arg.Channel,
		arg.Direction,
		arg.MessageType,
		arg.TemplateID,
		arg.Consent,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerContact,
		&i.Channel,
		&i.Direction,
		&i.MessageType,
		&i.TemplateID,
		&i.Consent,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationsByMerchant = `-- name: ListConversationsByMerchant :many
SELECT id, merchant_id, customer_contact, channel, direction, message_type, template_id, consent, created_at FROM conversations
WHERE merchant_id = $1 AND customer_contact = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListConversationsByMerchantParams struct {
	MerchantID      pgtype.UUID `json:"merchant_id"`
	CustomerContact string      `json:"customer_contact"`
	Limit           int32       `json:"limit"`
}

func (q *Queries) ListConversationsByMerchant(ctx context.Context, arg ListConversationsByMerchantParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByMerchant, arg.MerchantID, arg.CustomerContact, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CustomerContact,
			&i.Channel,
			&i.Direction,
			&i.MessageType,
			&i.TemplateID,
			&i.Consent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
