// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCustomer = `-- name: DeleteCustomer :execrows
DELETE FROM customers WHERE id = $1 AND merchant_id = $2
`

type DeleteCustomerParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomer, arg.ID, arg.MerchantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, merchant_id, name, contact, created_at, updated_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Contact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, merchant_id, name, contact, created_at, updated_at FROM customers WHERE merchant_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListCustomers(ctx context.Context, merchantID pgtype.UUID) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Contact,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :execrows
UPDATE customers SET name = $3, contact = $4, updated_at = now()
WHERE id = $1 AND merchant_id = $2
`

type UpdateCustomerParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
	Name       pgtype.Text `json:"name"`
	Contact    string      `json:"contact"`
}

// Ownership enforced in the WHERE clause, same pattern as
// UpdateMerchantLocation — the route path only carries the customer's
// own id, not the merchant id.
func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCustomer,
		arg.ID,
		arg.MerchantID,
		arg.Name,
		arg.Contact,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCustomer = `-- name: UpsertCustomer :one
INSERT INTO customers (merchant_id, contact, name)
VALUES ($1, $2, $3)
ON CONFLICT (merchant_id, contact) DO UPDATE
SET name = COALESCE(EXCLUDED.name, customers.name), updated_at = now()
RETURNING id, merchant_id, name, contact, created_at, updated_at
`

type UpsertCustomerParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Contact    string      `json:"contact"`
	Name       pgtype.Text `json:"name"`
}

// Best-effort auto-save (called after every invoice send) and the
// manual "+ Add Customer" path share this same query — both are really
// "remember this contact, keeping whatever name we already know unless
// a better one just showed up." COALESCE keeps an existing name intact
// when this particular call doesn't have one (EXCLUDED.name NULL).
func (q *Queries) UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, upsertCustomer, arg.MerchantID, arg.Contact, arg.Name)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Contact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
