// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delivery_options.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryOption = `-- name: CreateDeliveryOption :one
INSERT INTO delivery_options (merchant_id, type, contact_name, contact_phone, provider_key, deep_link_template, fee_handling_default, flat_fee_pesewas, service_zone)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, merchant_id, type, contact_name, contact_phone, provider_key, deep_link_template, fee_handling_default, status, created_at, updated_at, flat_fee_pesewas, service_zone
`

type CreateDeliveryOptionParams struct {
	MerchantID         pgtype.UUID `json:"merchant_id"`
	Type               string      `json:"type"`
	ContactName        pgtype.Text `json:"contact_name"`
	ContactPhone       pgtype.Text `json:"contact_phone"`
	ProviderKey        pgtype.Text `json:"provider_key"`
	DeepLinkTemplate   pgtype.Text `json:"deep_link_template"`
	FeeHandlingDefault string      `json:"fee_handling_default"`
	FlatFeePesewas     pgtype.Int8 `json:"flat_fee_pesewas"`
	ServiceZone        pgtype.Text `json:"service_zone"`
}

func (q *Queries) CreateDeliveryOption(ctx context.Context, arg CreateDeliveryOptionParams) (DeliveryOption, error) {
	row := q.db.QueryRow(ctx, createDeliveryOption,
		arg.MerchantID,
		arg.Type,
		arg.ContactName,
		arg.ContactPhone,
		arg.ProviderKey,
		arg.DeepLinkTemplate,
		arg.FeeHandlingDefault,
		arg.FlatFeePesewas,
		arg.ServiceZone,
	)
	var i DeliveryOption
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Type,
		&i.ContactName,
		&i.ContactPhone,
		&i.ProviderKey,
		&i.DeepLinkTemplate,
		&i.FeeHandlingDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FlatFeePesewas,
		&i.ServiceZone,
	)
	return i, err
}

const getDeliveryOption = `-- name: GetDeliveryOption :one
SELECT id, merchant_id, type, contact_name, contact_phone, provider_key, deep_link_template, fee_handling_default, status, created_at, updated_at, flat_fee_pesewas, service_zone FROM delivery_options WHERE id = $1
`

func (q *Queries) GetDeliveryOption(ctx context.Context, id pgtype.UUID) (DeliveryOption, error) {
	row := q.db.QueryRow(ctx, getDeliveryOption, id)
	var i DeliveryOption
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Type,
		&i.ContactName,
		&i.ContactPhone,
		&i.ProviderKey,
		&i.DeepLinkTemplate,
		&i.FeeHandlingDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FlatFeePesewas,
		&i.ServiceZone,
	)
	return i, err
}

const listDeliveryOptionsByMerchant = `-- name: ListDeliveryOptionsByMerchant :many
SELECT id, merchant_id, type, contact_name, contact_phone, provider_key, deep_link_template, fee_handling_default, status, created_at, updated_at, flat_fee_pesewas, service_zone FROM delivery_options
WHERE merchant_id = $1 AND status = 'active'
ORDER BY created_at
`

func (q *Queries) ListDeliveryOptionsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]DeliveryOption, error) {
	rows, err := q.db.Query(ctx, listDeliveryOptionsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryOption{}
	for rows.Next() {
		var i DeliveryOption
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Type,
			&i.ContactName,
			&i.ContactPhone,
			&i.ProviderKey,
			&i.DeepLinkTemplate,
			&i.FeeHandlingDefault,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FlatFeePesewas,
			&i.ServiceZone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeliveryOptionStatus = `-- name: SetDeliveryOptionStatus :execrows
UPDATE delivery_options SET status = $2 WHERE id = $1 AND merchant_id = $3
`

type SetDeliveryOptionStatusParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

// merchant_id in the WHERE clause — the route path only carries the
// delivery option's own id, not a merchant id, so ownership has to be
// enforced here against the caller's token instead.
func (q *Queries) SetDeliveryOptionStatus(ctx context.Context, arg SetDeliveryOptionStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDeliveryOptionStatus, arg.ID, arg.Status, arg.MerchantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDeliveryOption = `-- name: UpdateDeliveryOption :execrows
UPDATE delivery_options
SET contact_name = $2,
    contact_phone = $3,
    flat_fee_pesewas = $4,
    service_zone = $5,
    fee_handling_default = $6,
    status = $7
WHERE id = $1 AND merchant_id = $8
`

type UpdateDeliveryOptionParams struct {
	ID                 pgtype.UUID `json:"id"`
	ContactName        pgtype.Text `json:"contact_name"`
	ContactPhone       pgtype.Text `json:"contact_phone"`
	FlatFeePesewas     pgtype.Int8 `json:"flat_fee_pesewas"`
	ServiceZone        pgtype.Text `json:"service_zone"`
	FeeHandlingDefault string      `json:"fee_handling_default"`
	Status             string      `json:"status"`
	MerchantID         pgtype.UUID `json:"merchant_id"`
}

// Full edit — contact/provider details, flat fee/zone, and fee handling —
// used by the Delivery Settings screen's edit sheet and by the inline
// fee-handling selector on already-enabled catalog providers. Same
// ownership-in-WHERE pattern as SetDeliveryOptionStatus above.
func (q *Queries) UpdateDeliveryOption(ctx context.Context, arg UpdateDeliveryOptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDeliveryOption,
		arg.ID,
		arg.ContactName,
		arg.ContactPhone,
		arg.FlatFeePesewas,
		arg.ServiceZone,
		arg.FeeHandlingDefault,
		arg.Status,
		arg.MerchantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
