// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delivery_providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryProvider = `-- name: CreateDeliveryProvider :one
INSERT INTO delivery_providers (key, name, deep_link_template, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, key, name, deep_link_template, status, notes, created_at, updated_at
`

type CreateDeliveryProviderParams struct {
	Key              string      `json:"key"`
	Name             string      `json:"name"`
	DeepLinkTemplate string      `json:"deep_link_template"`
	Notes            pgtype.Text `json:"notes"`
}

func (q *Queries) CreateDeliveryProvider(ctx context.Context, arg CreateDeliveryProviderParams) (DeliveryProvider, error) {
	row := q.db.QueryRow(ctx, createDeliveryProvider,
		arg.Key,
		arg.Name,
		arg.DeepLinkTemplate,
		arg.Notes,
	)
	var i DeliveryProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.DeepLinkTemplate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeliveryProvider = `-- name: DeleteDeliveryProvider :exec
DELETE FROM delivery_providers WHERE id = $1
`

func (q *Queries) DeleteDeliveryProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeliveryProvider, id)
	return err
}

const listActiveDeliveryProviders = `-- name: ListActiveDeliveryProviders :many
SELECT id, key, name, deep_link_template, status, notes, created_at, updated_at FROM delivery_providers WHERE status = 'active' ORDER BY name
`

// Merchant-app side of the admin-maintained catalog (Section 4.11/9.4) —
// only what's actually active, unlike the admin list above which needs to
// see inactive/retired entries too for management.
func (q *Queries) ListActiveDeliveryProviders(ctx context.Context) ([]DeliveryProvider, error) {
	rows, err := q.db.Query(ctx, listActiveDeliveryProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryProvider{}
	for rows.Next() {
		var i DeliveryProvider
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.DeepLinkTemplate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryProviders = `-- name: ListDeliveryProviders :many
SELECT id, key, name, deep_link_template, status, notes, created_at, updated_at FROM delivery_providers ORDER BY name
`

func (q *Queries) ListDeliveryProviders(ctx context.Context) ([]DeliveryProvider, error) {
	rows, err := q.db.Query(ctx, listDeliveryProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryProvider{}
	for rows.Next() {
		var i DeliveryProvider
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.DeepLinkTemplate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryProvider = `-- name: UpdateDeliveryProvider :one
UPDATE delivery_providers
SET name = $2, deep_link_template = $3, status = $4, notes = $5
WHERE id = $1
RETURNING id, key, name, deep_link_template, status, notes, created_at, updated_at
`

type UpdateDeliveryProviderParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	DeepLinkTemplate string      `json:"deep_link_template"`
	Status           string      `json:"status"`
	Notes            pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateDeliveryProvider(ctx context.Context, arg UpdateDeliveryProviderParams) (DeliveryProvider, error) {
	row := q.db.QueryRow(ctx, updateDeliveryProvider,
		arg.ID,
		arg.Name,
		arg.DeepLinkTemplate,
		arg.Status,
		arg.Notes,
	)
	var i DeliveryProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.DeepLinkTemplate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
