// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: device_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE fcm_token = $1
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, fcmToken string) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, fcmToken)
	return err
}

const listDeviceTokensByMerchant = `-- name: ListDeviceTokensByMerchant :many
SELECT id, merchant_id, fcm_token, platform, created_at, updated_at FROM device_tokens WHERE merchant_id = $1
`

func (q *Queries) ListDeviceTokensByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.FcmToken,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (merchant_id, fcm_token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (fcm_token) DO UPDATE
  SET merchant_id = EXCLUDED.merchant_id, platform = EXCLUDED.platform
RETURNING id, merchant_id, fcm_token, platform, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	FcmToken   string      `json:"fcm_token"`
	Platform   string      `json:"platform"`
}

// Re-registering the same token (app relaunch) just bumps updated_at; a
// token that moved to a different merchant (see migration comment) is
// repointed rather than rejected.
func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken, arg.MerchantID, arg.FcmToken, arg.Platform)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.FcmToken,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
