// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: disputes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPaymentRefund = `-- name: AddPaymentRefund :one
UPDATE payments SET refunded_amount_pesewas = refunded_amount_pesewas + $1
WHERE id = $2
RETURNING id, invoice_id, psp_reference, method, amount_pesewas, status, paid_at, created_at, psp_fee_pesewas, settlement_id, refunded_amount_pesewas
`

type AddPaymentRefundParams struct {
	Amount int64       `json:"amount"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) AddPaymentRefund(ctx context.Context, arg AddPaymentRefundParams) (Payment, error) {
	row := q.db.QueryRow(ctx, addPaymentRefund, arg.Amount, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.PspReference,
		&i.Method,
		&i.AmountPesewas,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.PspFeePesewas,
		&i.SettlementID,
		&i.RefundedAmountPesewas,
	)
	return i, err
}

const createDispute = `-- name: CreateDispute :one
INSERT INTO disputes (invoice_id, reason_category, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, invoice_id, reason_category, description, status, resolution_notes, refund_payment_id, refund_amount_pesewas, created_by, resolved_by, resolved_at, created_at, updated_at
`

type CreateDisputeParams struct {
	InvoiceID      pgtype.UUID `json:"invoice_id"`
	ReasonCategory string      `json:"reason_category"`
	Description    pgtype.Text `json:"description"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, createDispute,
		arg.InvoiceID,
		arg.ReasonCategory,
		arg.Description,
		arg.CreatedBy,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ReasonCategory,
		&i.Description,
		&i.Status,
		&i.ResolutionNotes,
		&i.RefundPaymentID,
		&i.RefundAmountPesewas,
		&i.CreatedBy,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDispute = `-- name: GetDispute :one
SELECT id, invoice_id, reason_category, description, status, resolution_notes, refund_payment_id, refund_amount_pesewas, created_by, resolved_by, resolved_at, created_at, updated_at FROM disputes WHERE id = $1
`

func (q *Queries) GetDispute(ctx context.Context, id pgtype.UUID) (Dispute, error) {
	row := q.db.QueryRow(ctx, getDispute, id)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ReasonCategory,
		&i.Description,
		&i.Status,
		&i.ResolutionNotes,
		&i.RefundPaymentID,
		&i.RefundAmountPesewas,
		&i.CreatedBy,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDisputesAdmin = `-- name: ListDisputesAdmin :many
SELECT d.id, d.invoice_id, d.reason_category, d.description, d.status, d.resolution_notes, d.refund_payment_id, d.refund_amount_pesewas, d.created_by, d.resolved_by, d.resolved_at, d.created_at, d.updated_at, i.reference AS invoice_reference, i.customer_contact, m.business_name AS merchant_business_name
FROM disputes d
JOIN invoices i ON i.id = d.invoice_id
JOIN merchants m ON m.id = i.merchant_id
WHERE ($1::text = '' OR d.status = $1::text)
ORDER BY d.created_at DESC
LIMIT $3 OFFSET $2
`

type ListDisputesAdminParams struct {
	StatusFilter string `json:"status_filter"`
	RowOffset    int32  `json:"row_offset"`
	RowLimit     int32  `json:"row_limit"`
}

type ListDisputesAdminRow struct {
	ID                   pgtype.UUID        `json:"id"`
	InvoiceID            pgtype.UUID        `json:"invoice_id"`
	ReasonCategory       string             `json:"reason_category"`
	Description          pgtype.Text        `json:"description"`
	Status               string             `json:"status"`
	ResolutionNotes      pgtype.Text        `json:"resolution_notes"`
	RefundPaymentID      pgtype.UUID        `json:"refund_payment_id"`
	RefundAmountPesewas  pgtype.Int8        `json:"refund_amount_pesewas"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	ResolvedBy           pgtype.UUID        `json:"resolved_by"`
	ResolvedAt           pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	InvoiceReference     string             `json:"invoice_reference"`
	CustomerContact      string             `json:"customer_contact"`
	MerchantBusinessName string             `json:"merchant_business_name"`
}

func (q *Queries) ListDisputesAdmin(ctx context.Context, arg ListDisputesAdminParams) ([]ListDisputesAdminRow, error) {
	rows, err := q.db.Query(ctx, listDisputesAdmin, arg.StatusFilter, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisputesAdminRow{}
	for rows.Next() {
		var i ListDisputesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ReasonCategory,
			&i.Description,
			&i.Status,
			&i.ResolutionNotes,
			&i.RefundPaymentID,
			&i.RefundAmountPesewas,
			&i.CreatedBy,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InvoiceReference,
			&i.CustomerContact,
			&i.MerchantBusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveDispute = `-- name: ResolveDispute :one
UPDATE disputes
SET status = $1, resolution_notes = $2,
    refund_payment_id = $3, refund_amount_pesewas = $4,
    resolved_by = $5, resolved_at = now()
WHERE id = $6
RETURNING id, invoice_id, reason_category, description, status, resolution_notes, refund_payment_id, refund_amount_pesewas, created_by, resolved_by, resolved_at, created_at, updated_at
`

type ResolveDisputeParams struct {
	Status              string      `json:"status"`
	ResolutionNotes     pgtype.Text `json:"resolution_notes"`
	RefundPaymentID     pgtype.UUID `json:"refund_payment_id"`
	RefundAmountPesewas pgtype.Int8 `json:"refund_amount_pesewas"`
	ResolvedBy          pgtype.UUID `json:"resolved_by"`
	ID                  pgtype.UUID `json:"id"`
}

func (q *Queries) ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, resolveDispute,
		arg.Status,
		arg.ResolutionNotes,
		arg.RefundPaymentID,
		arg.RefundAmountPesewas,
		arg.ResolvedBy,
		arg.ID,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ReasonCategory,
		&i.Description,
		&i.Status,
		&i.ResolutionNotes,
		&i.RefundPaymentID,
		&i.RefundAmountPesewas,
		&i.CreatedBy,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setDisputeStatus = `-- name: SetDisputeStatus :one
UPDATE disputes SET status = $2 WHERE id = $1
RETURNING id, invoice_id, reason_category, description, status, resolution_notes, refund_payment_id, refund_amount_pesewas, created_by, resolved_by, resolved_at, created_at, updated_at
`

type SetDisputeStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Non-terminal transition only (e.g. open -> investigating) — no
// resolution fields; see ResolveDispute for the terminal transitions.
func (q *Queries) SetDisputeStatus(ctx context.Context, arg SetDisputeStatusParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, setDisputeStatus, arg.ID, arg.Status)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ReasonCategory,
		&i.Description,
		&i.Status,
		&i.ResolutionNotes,
		&i.RefundPaymentID,
		&i.RefundAmountPesewas,
		&i.CreatedBy,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
