// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: email_verifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (merchant_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, merchant_id, token, expires_at, used_at, created_at
`

type CreateEmailVerificationParams struct {
	MerchantID pgtype.UUID        `json:"merchant_id"`
	Token      string             `json:"token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, createEmailVerification, arg.MerchantID, arg.Token, arg.ExpiresAt)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailVerificationByToken = `-- name: GetEmailVerificationByToken :one
SELECT id, merchant_id, token, expires_at, used_at, created_at FROM email_verifications WHERE token = $1
`

func (q *Queries) GetEmailVerificationByToken(ctx context.Context, token string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByToken, token)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :exec
UPDATE email_verifications SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerificationUsed, id)
	return err
}

const markMerchantEmailVerified = `-- name: MarkMerchantEmailVerified :one
UPDATE merchants SET email_verified_at = now() WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id
`

func (q *Queries) MarkMerchantEmailVerified(ctx context.Context, id pgtype.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, markMerchantEmailVerified, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
	)
	return i, err
}
