// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: feature_flags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFeatureFlagMerchant = `-- name: AddFeatureFlagMerchant :exec
INSERT INTO feature_flag_merchants (feature_flag_id, merchant_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFeatureFlagMerchantParams struct {
	FeatureFlagID pgtype.UUID `json:"feature_flag_id"`
	MerchantID    pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) AddFeatureFlagMerchant(ctx context.Context, arg AddFeatureFlagMerchantParams) error {
	_, err := q.db.Exec(ctx, addFeatureFlagMerchant, arg.FeatureFlagID, arg.MerchantID)
	return err
}

const getFeatureFlag = `-- name: GetFeatureFlag :one
SELECT id, key, name, description, enabled_globally, created_at, updated_at FROM feature_flags WHERE id = $1
`

func (q *Queries) GetFeatureFlag(ctx context.Context, id pgtype.UUID) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, getFeatureFlag, id)
	var i FeatureFlag
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.EnabledGlobally,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeatureFlagStatusForMerchant = `-- name: GetFeatureFlagStatusForMerchant :one
SELECT COALESCE(
  (SELECT ff.enabled_globally OR EXISTS (
     SELECT 1 FROM feature_flag_merchants ffm
     WHERE ffm.feature_flag_id = ff.id AND ffm.merchant_id = $1
   )
   FROM feature_flags ff
   WHERE ff.key = $2),
  false
)::bool AS enabled
`

type GetFeatureFlagStatusForMerchantParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Key        string      `json:"key"`
}

// Enabled if flipped on for everyone, or this merchant is specifically
// opted in during a staged rollout (Section 7.4). Returns false (not an
// error) when the key doesn't exist, so callers checking a not-yet-seeded
// flag key just see "off" rather than needing separate not-found handling.
func (q *Queries) GetFeatureFlagStatusForMerchant(ctx context.Context, arg GetFeatureFlagStatusForMerchantParams) (bool, error) {
	row := q.db.QueryRow(ctx, getFeatureFlagStatusForMerchant, arg.MerchantID, arg.Key)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const listFeatureFlagMerchants = `-- name: ListFeatureFlagMerchants :many
SELECT ffm.merchant_id, m.business_name
FROM feature_flag_merchants ffm
JOIN merchants m ON m.id = ffm.merchant_id
WHERE ffm.feature_flag_id = $1
ORDER BY m.business_name
`

type ListFeatureFlagMerchantsRow struct {
	MerchantID   pgtype.UUID `json:"merchant_id"`
	BusinessName string      `json:"business_name"`
}

func (q *Queries) ListFeatureFlagMerchants(ctx context.Context, featureFlagID pgtype.UUID) ([]ListFeatureFlagMerchantsRow, error) {
	rows, err := q.db.Query(ctx, listFeatureFlagMerchants, featureFlagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeatureFlagMerchantsRow{}
	for rows.Next() {
		var i ListFeatureFlagMerchantsRow
		if err := rows.Scan(&i.MerchantID, &i.BusinessName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureFlags = `-- name: ListFeatureFlags :many
SELECT id, key, name, description, enabled_globally, created_at, updated_at FROM feature_flags ORDER BY name
`

func (q *Queries) ListFeatureFlags(ctx context.Context) ([]FeatureFlag, error) {
	rows, err := q.db.Query(ctx, listFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureFlag{}
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.EnabledGlobally,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFeatureFlagMerchant = `-- name: RemoveFeatureFlagMerchant :exec
DELETE FROM feature_flag_merchants WHERE feature_flag_id = $1 AND merchant_id = $2
`

type RemoveFeatureFlagMerchantParams struct {
	FeatureFlagID pgtype.UUID `json:"feature_flag_id"`
	MerchantID    pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) RemoveFeatureFlagMerchant(ctx context.Context, arg RemoveFeatureFlagMerchantParams) error {
	_, err := q.db.Exec(ctx, removeFeatureFlagMerchant, arg.FeatureFlagID, arg.MerchantID)
	return err
}

const setFeatureFlagGlobal = `-- name: SetFeatureFlagGlobal :one
UPDATE feature_flags SET enabled_globally = $2 WHERE id = $1
RETURNING id, key, name, description, enabled_globally, created_at, updated_at
`

type SetFeatureFlagGlobalParams struct {
	ID              pgtype.UUID `json:"id"`
	EnabledGlobally bool        `json:"enabled_globally"`
}

func (q *Queries) SetFeatureFlagGlobal(ctx context.Context, arg SetFeatureFlagGlobalParams) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, setFeatureFlagGlobal, arg.ID, arg.EnabledGlobally)
	var i FeatureFlag
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.EnabledGlobally,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
