// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: fee_rules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFeeRuleByMerchant = `-- name: GetFeeRuleByMerchant :one
SELECT id, merchant_id, commission_bps, allocation_type, created_at, updated_at FROM fee_rules WHERE merchant_id = $1
`

func (q *Queries) GetFeeRuleByMerchant(ctx context.Context, merchantID pgtype.UUID) (FeeRule, error) {
	row := q.db.QueryRow(ctx, getFeeRuleByMerchant, merchantID)
	var i FeeRule
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CommissionBps,
		&i.AllocationType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGlobalFeeRule = `-- name: GetGlobalFeeRule :one
SELECT id, merchant_id, commission_bps, allocation_type, created_at, updated_at FROM fee_rules WHERE merchant_id IS NULL
`

func (q *Queries) GetGlobalFeeRule(ctx context.Context) (FeeRule, error) {
	row := q.db.QueryRow(ctx, getGlobalFeeRule)
	var i FeeRule
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CommissionBps,
		&i.AllocationType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGlobalFeeRule = `-- name: UpsertGlobalFeeRule :one
INSERT INTO fee_rules (merchant_id, commission_bps, allocation_type)
VALUES (NULL, $1, $2)
ON CONFLICT ((1)) WHERE merchant_id IS NULL DO UPDATE
  SET commission_bps = EXCLUDED.commission_bps,
      allocation_type = EXCLUDED.allocation_type
RETURNING id, merchant_id, commission_bps, allocation_type, created_at, updated_at
`

type UpsertGlobalFeeRuleParams struct {
	CommissionBps  int32  `json:"commission_bps"`
	AllocationType string `json:"allocation_type"`
}

func (q *Queries) UpsertGlobalFeeRule(ctx context.Context, arg UpsertGlobalFeeRuleParams) (FeeRule, error) {
	row := q.db.QueryRow(ctx, upsertGlobalFeeRule, arg.CommissionBps, arg.AllocationType)
	var i FeeRule
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CommissionBps,
		&i.AllocationType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMerchantFeeRule = `-- name: UpsertMerchantFeeRule :one
INSERT INTO fee_rules (merchant_id, commission_bps, allocation_type)
VALUES ($1, $2, $3)
ON CONFLICT (merchant_id) WHERE merchant_id IS NOT NULL DO UPDATE
  SET commission_bps = EXCLUDED.commission_bps,
      allocation_type = EXCLUDED.allocation_type
RETURNING id, merchant_id, commission_bps, allocation_type, created_at, updated_at
`

type UpsertMerchantFeeRuleParams struct {
	MerchantID     pgtype.UUID `json:"merchant_id"`
	CommissionBps  int32       `json:"commission_bps"`
	AllocationType string      `json:"allocation_type"`
}

func (q *Queries) UpsertMerchantFeeRule(ctx context.Context, arg UpsertMerchantFeeRuleParams) (FeeRule, error) {
	row := q.db.QueryRow(ctx, upsertMerchantFeeRule, arg.MerchantID, arg.CommissionBps, arg.AllocationType)
	var i FeeRule
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CommissionBps,
		&i.AllocationType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
