// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: integrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIntegration = `-- name: GetIntegration :one
SELECT id, provider_key, category, built, secret_value, secret_updated_at, secret_updated_by, notes, created_at, updated_at FROM integrations WHERE provider_key = $1
`

func (q *Queries) GetIntegration(ctx context.Context, providerKey string) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegration, providerKey)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.Category,
		&i.Built,
		&i.SecretValue,
		&i.SecretUpdatedAt,
		&i.SecretUpdatedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, provider_key, category, built, secret_value, secret_updated_at, secret_updated_by, notes, created_at, updated_at FROM integrations ORDER BY built DESC, category
`

func (q *Queries) ListIntegrations(ctx context.Context) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.ProviderKey,
			&i.Category,
			&i.Built,
			&i.SecretValue,
			&i.SecretUpdatedAt,
			&i.SecretUpdatedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIntegrationSecret = `-- name: SetIntegrationSecret :one
UPDATE integrations
SET secret_value = $2, secret_updated_at = now(), secret_updated_by = $3
WHERE provider_key = $1
RETURNING id, provider_key, category, built, secret_value, secret_updated_at, secret_updated_by, notes, created_at, updated_at
`

type SetIntegrationSecretParams struct {
	ProviderKey     string      `json:"provider_key"`
	SecretValue     pgtype.Text `json:"secret_value"`
	SecretUpdatedBy pgtype.UUID `json:"secret_updated_by"`
}

func (q *Queries) SetIntegrationSecret(ctx context.Context, arg SetIntegrationSecretParams) (Integration, error) {
	row := q.db.QueryRow(ctx, setIntegrationSecret, arg.ProviderKey, arg.SecretValue, arg.SecretUpdatedBy)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.Category,
		&i.Built,
		&i.SecretValue,
		&i.SecretUpdatedAt,
		&i.SecretUpdatedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIntegrationNotes = `-- name: UpdateIntegrationNotes :one
UPDATE integrations SET notes = $2
WHERE provider_key = $1
RETURNING id, provider_key, category, built, secret_value, secret_updated_at, secret_updated_by, notes, created_at, updated_at
`

type UpdateIntegrationNotesParams struct {
	ProviderKey string      `json:"provider_key"`
	Notes       pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateIntegrationNotes(ctx context.Context, arg UpdateIntegrationNotesParams) (Integration, error) {
	row := q.db.QueryRow(ctx, updateIntegrationNotes, arg.ProviderKey, arg.Notes)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.Category,
		&i.Built,
		&i.SecretValue,
		&i.SecretUpdatedAt,
		&i.SecretUpdatedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
