// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: invoices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
  merchant_id, order_request_id, reference, customer_contact,
  subtotal_pesewas, service_charge_pesewas, service_charge_allocation, total_pesewas,
  delivery_option_id, delivery_address, delivery_fee_handling, delivery_fee_pesewas, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, merchant_id, order_request_id, reference, customer_contact, subtotal_pesewas, service_charge_pesewas, service_charge_allocation, total_pesewas, status, delivery_option_id, delivery_address, delivery_fee_handling, delivery_fee_pesewas, expires_at, created_at, updated_at
`

type CreateInvoiceParams struct {
	MerchantID              pgtype.UUID        `json:"merchant_id"`
	OrderRequestID          pgtype.UUID        `json:"order_request_id"`
	Reference               string             `json:"reference"`
	CustomerContact         string             `json:"customer_contact"`
	SubtotalPesewas         int64              `json:"subtotal_pesewas"`
	ServiceChargePesewas    int64              `json:"service_charge_pesewas"`
	ServiceChargeAllocation string             `json:"service_charge_allocation"`
	TotalPesewas            int64              `json:"total_pesewas"`
	DeliveryOptionID        pgtype.UUID        `json:"delivery_option_id"`
	DeliveryAddress         pgtype.Text        `json:"delivery_address"`
	DeliveryFeeHandling     pgtype.Text        `json:"delivery_fee_handling"`
	DeliveryFeePesewas      pgtype.Int8        `json:"delivery_fee_pesewas"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.MerchantID,
		arg.OrderRequestID,
		arg.Reference,
		arg.CustomerContact,
		arg.SubtotalPesewas,
		arg.ServiceChargePesewas,
		arg.ServiceChargeAllocation,
		arg.TotalPesewas,
		arg.DeliveryOptionID,
		arg.DeliveryAddress,
		arg.DeliveryFeeHandling,
		arg.DeliveryFeePesewas,
		arg.ExpiresAt,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.OrderRequestID,
		&i.Reference,
		&i.CustomerContact,
		&i.SubtotalPesewas,
		&i.ServiceChargePesewas,
		&i.ServiceChargeAllocation,
		&i.TotalPesewas,
		&i.Status,
		&i.DeliveryOptionID,
		&i.DeliveryAddress,
		&i.DeliveryFeeHandling,
		&i.DeliveryFeePesewas,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvoiceLineItem = `-- name: CreateInvoiceLineItem :one
INSERT INTO invoice_line_items (invoice_id, item_id, description, unit_price_pesewas, quantity, line_total_pesewas)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, invoice_id, item_id, description, unit_price_pesewas, quantity, line_total_pesewas
`

type CreateInvoiceLineItemParams struct {
	InvoiceID        pgtype.UUID `json:"invoice_id"`
	ItemID           pgtype.UUID `json:"item_id"`
	Description      string      `json:"description"`
	UnitPricePesewas int64       `json:"unit_price_pesewas"`
	Quantity         int32       `json:"quantity"`
	LineTotalPesewas int64       `json:"line_total_pesewas"`
}

func (q *Queries) CreateInvoiceLineItem(ctx context.Context, arg CreateInvoiceLineItemParams) (InvoiceLineItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceLineItem,
		arg.InvoiceID,
		arg.ItemID,
		arg.Description,
		arg.UnitPricePesewas,
		arg.Quantity,
		arg.LineTotalPesewas,
	)
	var i InvoiceLineItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ItemID,
		&i.Description,
		&i.UnitPricePesewas,
		&i.Quantity,
		&i.LineTotalPesewas,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, merchant_id, order_request_id, reference, customer_contact, subtotal_pesewas, service_charge_pesewas, service_charge_allocation, total_pesewas, status, delivery_option_id, delivery_address, delivery_fee_handling, delivery_fee_pesewas, expires_at, created_at, updated_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id pgtype.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.OrderRequestID,
		&i.Reference,
		&i.CustomerContact,
		&i.SubtotalPesewas,
		&i.ServiceChargePesewas,
		&i.ServiceChargeAllocation,
		&i.TotalPesewas,
		&i.Status,
		&i.DeliveryOptionID,
		&i.DeliveryAddress,
		&i.DeliveryFeeHandling,
		&i.DeliveryFeePesewas,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByReference = `-- name: GetInvoiceByReference :one
SELECT id, merchant_id, order_request_id, reference, customer_contact, subtotal_pesewas, service_charge_pesewas, service_charge_allocation, total_pesewas, status, delivery_option_id, delivery_address, delivery_fee_handling, delivery_fee_pesewas, expires_at, created_at, updated_at FROM invoices WHERE reference = $1
`

func (q *Queries) GetInvoiceByReference(ctx context.Context, reference string) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByReference, reference)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.OrderRequestID,
		&i.Reference,
		&i.CustomerContact,
		&i.SubtotalPesewas,
		&i.ServiceChargePesewas,
		&i.ServiceChargeAllocation,
		&i.TotalPesewas,
		&i.Status,
		&i.DeliveryOptionID,
		&i.DeliveryAddress,
		&i.DeliveryFeeHandling,
		&i.DeliveryFeePesewas,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvoiceLineItems = `-- name: ListInvoiceLineItems :many
SELECT id, invoice_id, item_id, description, unit_price_pesewas, quantity, line_total_pesewas FROM invoice_line_items WHERE invoice_id = $1
`

func (q *Queries) ListInvoiceLineItems(ctx context.Context, invoiceID pgtype.UUID) ([]InvoiceLineItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceLineItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceLineItem{}
	for rows.Next() {
		var i InvoiceLineItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ItemID,
			&i.Description,
			&i.UnitPricePesewas,
			&i.Quantity,
			&i.LineTotalPesewas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByMerchant = `-- name: ListInvoicesByMerchant :many
SELECT id, merchant_id, order_request_id, reference, customer_contact, subtotal_pesewas, service_charge_pesewas, service_charge_allocation, total_pesewas, status, delivery_option_id, delivery_address, delivery_fee_handling, delivery_fee_pesewas, expires_at, created_at, updated_at FROM invoices
WHERE merchant_id = $1
  AND ($4::text = '' OR status = $4::text)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesByMerchantParams struct {
	MerchantID   pgtype.UUID `json:"merchant_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	StatusFilter string      `json:"status_filter"`
}

func (q *Queries) ListInvoicesByMerchant(ctx context.Context, arg ListInvoicesByMerchantParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByMerchant,
		arg.MerchantID,
		arg.Limit,
		arg.Offset,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.OrderRequestID,
			&i.Reference,
			&i.CustomerContact,
			&i.SubtotalPesewas,
			&i.ServiceChargePesewas,
			&i.ServiceChargeAllocation,
			&i.TotalPesewas,
			&i.Status,
			&i.DeliveryOptionID,
			&i.DeliveryAddress,
			&i.DeliveryFeeHandling,
			&i.DeliveryFeePesewas,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInvoiceStatus = `-- name: SetInvoiceStatus :one
UPDATE invoices SET status = $2 WHERE id = $1
RETURNING id, merchant_id, order_request_id, reference, customer_contact, subtotal_pesewas, service_charge_pesewas, service_charge_allocation, total_pesewas, status, delivery_option_id, delivery_address, delivery_fee_handling, delivery_fee_pesewas, expires_at, created_at, updated_at
`

type SetInvoiceStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetInvoiceStatus(ctx context.Context, arg SetInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, setInvoiceStatus, arg.ID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.OrderRequestID,
		&i.Reference,
		&i.CustomerContact,
		&i.SubtotalPesewas,
		&i.ServiceChargePesewas,
		&i.ServiceChargeAllocation,
		&i.TotalPesewas,
		&i.Status,
		&i.DeliveryOptionID,
		&i.DeliveryAddress,
		&i.DeliveryFeeHandling,
		&i.DeliveryFeePesewas,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
