// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveItem = `-- name: ArchiveItem :execrows
UPDATE items SET archived_at = now() WHERE id = $1 AND merchant_id = $2
`

type ArchiveItemParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) ArchiveItem(ctx context.Context, arg ArchiveItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveItem, arg.ID, arg.MerchantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (merchant_id, name, unit_price_pesewas, qty_unit, image_url, availability_status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, merchant_id, name, unit_price_pesewas, qty_unit, image_url, availability_status, archived_at, created_at, updated_at
`

type CreateItemParams struct {
	MerchantID         pgtype.UUID `json:"merchant_id"`
	Name               string      `json:"name"`
	UnitPricePesewas   int64       `json:"unit_price_pesewas"`
	QtyUnit            pgtype.Text `json:"qty_unit"`
	ImageUrl           pgtype.Text `json:"image_url"`
	AvailabilityStatus string      `json:"availability_status"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.MerchantID,
		arg.Name,
		arg.UnitPricePesewas,
		arg.QtyUnit,
		arg.ImageUrl,
		arg.AvailabilityStatus,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.UnitPricePesewas,
		&i.QtyUnit,
		&i.ImageUrl,
		&i.AvailabilityStatus,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, merchant_id, name, unit_price_pesewas, qty_unit, image_url, availability_status, archived_at, created_at, updated_at FROM items WHERE id = $1
`

// Single-param, unscoped by merchant — used internally by the invoice
// engine (resolveLineItems), which does its own explicit ownership compare
// against the item it fetches. Route handlers should use
// GetItemOwnedByMerchant instead.
func (q *Queries) GetItem(ctx context.Context, id pgtype.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.UnitPricePesewas,
		&i.QtyUnit,
		&i.ImageUrl,
		&i.AvailabilityStatus,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemOwnedByMerchant = `-- name: GetItemOwnedByMerchant :one
SELECT id, merchant_id, name, unit_price_pesewas, qty_unit, image_url, availability_status, archived_at, created_at, updated_at FROM items WHERE id = $1 AND merchant_id = $2
`

type GetItemOwnedByMerchantParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) GetItemOwnedByMerchant(ctx context.Context, arg GetItemOwnedByMerchantParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItemOwnedByMerchant, arg.ID, arg.MerchantID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.UnitPricePesewas,
		&i.QtyUnit,
		&i.ImageUrl,
		&i.AvailabilityStatus,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemsByMerchant = `-- name: ListItemsByMerchant :many
SELECT id, merchant_id, name, unit_price_pesewas, qty_unit, image_url, availability_status, archived_at, created_at, updated_at FROM items
WHERE merchant_id = $1 AND archived_at IS NULL
ORDER BY name
`

func (q *Queries) ListItemsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.UnitPricePesewas,
			&i.QtyUnit,
			&i.ImageUrl,
			&i.AvailabilityStatus,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET name = $2,
    unit_price_pesewas = $3,
    qty_unit = $4,
    image_url = $5,
    availability_status = $6
WHERE id = $1 AND merchant_id = $7
RETURNING id, merchant_id, name, unit_price_pesewas, qty_unit, image_url, availability_status, archived_at, created_at, updated_at
`

type UpdateItemParams struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	UnitPricePesewas   int64       `json:"unit_price_pesewas"`
	QtyUnit            pgtype.Text `json:"qty_unit"`
	ImageUrl           pgtype.Text `json:"image_url"`
	AvailabilityStatus string      `json:"availability_status"`
	MerchantID         pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.Name,
		arg.UnitPricePesewas,
		arg.QtyUnit,
		arg.ImageUrl,
		arg.AvailabilityStatus,
		arg.MerchantID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.UnitPricePesewas,
		&i.QtyUnit,
		&i.ImageUrl,
		&i.AvailabilityStatus,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
