// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: kyc_submissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKYCSubmission = `-- name: CreateKYCSubmission :one
INSERT INTO kyc_submissions (
  merchant_id, business_type, requested_tier, ghana_card_number, selfie_photo_path,
  business_reg_number, tin, entity_type, registration_cert_path, notes
) VALUES (
  $1, $2,
  CASE WHEN $2::text = 'registered' THEN 2 ELSE 1 END,
  $3, $4,
  $5, $6, $7,
  $8, $9
)
RETURNING id, merchant_id, requested_tier, ghana_card_number, business_reg_number, notes, status, reviewer_notes, reviewed_by, reviewed_at, created_at, updated_at, selfie_photo_path, business_type, tin, entity_type, registration_cert_path
`

type CreateKYCSubmissionParams struct {
	MerchantID           pgtype.UUID `json:"merchant_id"`
	BusinessType         string      `json:"business_type"`
	GhanaCardNumber      string      `json:"ghana_card_number"`
	SelfiePhotoPath      pgtype.Text `json:"selfie_photo_path"`
	BusinessRegNumber    pgtype.Text `json:"business_reg_number"`
	Tin                  pgtype.Text `json:"tin"`
	EntityType           pgtype.Text `json:"entity_type"`
	RegistrationCertPath pgtype.Text `json:"registration_cert_path"`
	Notes                pgtype.Text `json:"notes"`
}

// requested_tier is not caller-chosen: the schema pins informal to 1 and
// registered to 2, so the tier always matches the evidence reviewed.
func (q *Queries) CreateKYCSubmission(ctx context.Context, arg CreateKYCSubmissionParams) (KycSubmission, error) {
	row := q.db.QueryRow(ctx, createKYCSubmission,
		arg.MerchantID,
		arg.BusinessType,
		arg.GhanaCardNumber,
		arg.SelfiePhotoPath,
		arg.BusinessRegNumber,
		arg.Tin,
		arg.EntityType,
		arg.RegistrationCertPath,
		arg.Notes,
	)
	var i KycSubmission
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.RequestedTier,
		&i.GhanaCardNumber,
		&i.BusinessRegNumber,
		&i.Notes,
		&i.Status,
		&i.ReviewerNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelfiePhotoPath,
		&i.BusinessType,
		&i.Tin,
		&i.EntityType,
		&i.RegistrationCertPath,
	)
	return i, err
}

const getKYCSubmission = `-- name: GetKYCSubmission :one
SELECT id, merchant_id, requested_tier, ghana_card_number, business_reg_number, notes, status, reviewer_notes, reviewed_by, reviewed_at, created_at, updated_at, selfie_photo_path, business_type, tin, entity_type, registration_cert_path FROM kyc_submissions WHERE id = $1
`

func (q *Queries) GetKYCSubmission(ctx context.Context, id pgtype.UUID) (KycSubmission, error) {
	row := q.db.QueryRow(ctx, getKYCSubmission, id)
	var i KycSubmission
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.RequestedTier,
		&i.GhanaCardNumber,
		&i.BusinessRegNumber,
		&i.Notes,
		&i.Status,
		&i.ReviewerNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelfiePhotoPath,
		&i.BusinessType,
		&i.Tin,
		&i.EntityType,
		&i.RegistrationCertPath,
	)
	return i, err
}

const getOpenKYCSubmissionByMerchant = `-- name: GetOpenKYCSubmissionByMerchant :one
SELECT id, merchant_id, requested_tier, ghana_card_number, business_reg_number, notes, status, reviewer_notes, reviewed_by, reviewed_at, created_at, updated_at, selfie_photo_path, business_type, tin, entity_type, registration_cert_path FROM kyc_submissions
WHERE merchant_id = $1 AND status IN ('pending', 'more_info_requested')
LIMIT 1
`

func (q *Queries) GetOpenKYCSubmissionByMerchant(ctx context.Context, merchantID pgtype.UUID) (KycSubmission, error) {
	row := q.db.QueryRow(ctx, getOpenKYCSubmissionByMerchant, merchantID)
	var i KycSubmission
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.RequestedTier,
		&i.GhanaCardNumber,
		&i.BusinessRegNumber,
		&i.Notes,
		&i.Status,
		&i.ReviewerNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelfiePhotoPath,
		&i.BusinessType,
		&i.Tin,
		&i.EntityType,
		&i.RegistrationCertPath,
	)
	return i, err
}

const listKYCSubmissionsAdmin = `-- name: ListKYCSubmissionsAdmin :many
SELECT s.id, s.merchant_id, s.requested_tier, s.ghana_card_number, s.business_reg_number, s.notes, s.status, s.reviewer_notes, s.reviewed_by, s.reviewed_at, s.created_at, s.updated_at, s.selfie_photo_path, s.business_type, s.tin, s.entity_type, s.registration_cert_path, m.business_name AS merchant_business_name
FROM kyc_submissions s
JOIN merchants m ON m.id = s.merchant_id
WHERE ($1::text = '' OR s.status = $1::text)
ORDER BY s.created_at ASC
LIMIT $3 OFFSET $2
`

type ListKYCSubmissionsAdminParams struct {
	StatusFilter string `json:"status_filter"`
	RowOffset    int32  `json:"row_offset"`
	RowLimit     int32  `json:"row_limit"`
}

type ListKYCSubmissionsAdminRow struct {
	ID                   pgtype.UUID        `json:"id"`
	MerchantID           pgtype.UUID        `json:"merchant_id"`
	RequestedTier        int16              `json:"requested_tier"`
	GhanaCardNumber      string             `json:"ghana_card_number"`
	BusinessRegNumber    pgtype.Text        `json:"business_reg_number"`
	Notes                pgtype.Text        `json:"notes"`
	Status               string             `json:"status"`
	ReviewerNotes        pgtype.Text        `json:"reviewer_notes"`
	ReviewedBy           pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	SelfiePhotoPath      pgtype.Text        `json:"selfie_photo_path"`
	BusinessType         string             `json:"business_type"`
	Tin                  pgtype.Text        `json:"tin"`
	EntityType           pgtype.Text        `json:"entity_type"`
	RegistrationCertPath pgtype.Text        `json:"registration_cert_path"`
	MerchantBusinessName string             `json:"merchant_business_name"`
}

func (q *Queries) ListKYCSubmissionsAdmin(ctx context.Context, arg ListKYCSubmissionsAdminParams) ([]ListKYCSubmissionsAdminRow, error) {
	rows, err := q.db.Query(ctx, listKYCSubmissionsAdmin, arg.StatusFilter, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKYCSubmissionsAdminRow{}
	for rows.Next() {
		var i ListKYCSubmissionsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.RequestedTier,
			&i.GhanaCardNumber,
			&i.BusinessRegNumber,
			&i.Notes,
			&i.Status,
			&i.ReviewerNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SelfiePhotoPath,
			&i.BusinessType,
			&i.Tin,
			&i.EntityType,
			&i.RegistrationCertPath,
			&i.MerchantBusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKYCSubmissionsByMerchant = `-- name: ListKYCSubmissionsByMerchant :many
SELECT id, merchant_id, requested_tier, ghana_card_number, business_reg_number, notes, status, reviewer_notes, reviewed_by, reviewed_at, created_at, updated_at, selfie_photo_path, business_type, tin, entity_type, registration_cert_path FROM kyc_submissions WHERE merchant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListKYCSubmissionsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]KycSubmission, error) {
	rows, err := q.db.Query(ctx, listKYCSubmissionsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KycSubmission{}
	for rows.Next() {
		var i KycSubmission
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.RequestedTier,
			&i.GhanaCardNumber,
			&i.BusinessRegNumber,
			&i.Notes,
			&i.Status,
			&i.ReviewerNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SelfiePhotoPath,
			&i.BusinessType,
			&i.Tin,
			&i.EntityType,
			&i.RegistrationCertPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resubmitKYCSubmission = `-- name: ResubmitKYCSubmission :one
UPDATE kyc_submissions
SET business_type = $1,
    requested_tier = CASE WHEN $1::text = 'registered' THEN 2 ELSE 1 END,
    ghana_card_number = $2,
    selfie_photo_path = $3,
    business_reg_number = $4,
    tin = $5,
    entity_type = $6,
    registration_cert_path = $7,
    notes = $8,
    status = 'pending', reviewer_notes = NULL, reviewed_by = NULL, reviewed_at = NULL
WHERE id = $9
RETURNING id, merchant_id, requested_tier, ghana_card_number, business_reg_number, notes, status, reviewer_notes, reviewed_by, reviewed_at, created_at, updated_at, selfie_photo_path, business_type, tin, entity_type, registration_cert_path
`

type ResubmitKYCSubmissionParams struct {
	BusinessType         string      `json:"business_type"`
	GhanaCardNumber      string      `json:"ghana_card_number"`
	SelfiePhotoPath      pgtype.Text `json:"selfie_photo_path"`
	BusinessRegNumber    pgtype.Text `json:"business_reg_number"`
	Tin                  pgtype.Text `json:"tin"`
	EntityType           pgtype.Text `json:"entity_type"`
	RegistrationCertPath pgtype.Text `json:"registration_cert_path"`
	Notes                pgtype.Text `json:"notes"`
	ID                   pgtype.UUID `json:"id"`
}

// Reuses the existing row after a more_info_requested response instead of
// inserting a second one — kyc_submissions_one_open_per_merchant would
// reject a second open row anyway, and this is the correct UX: the
// reviewer's original notes/decision get replaced by the fresh review cycle.
// A resubmission may also switch fork — an informal trader who registers
// their business between review cycles resubmits as 'registered', and
// requested_tier moves with it.
func (q *Queries) ResubmitKYCSubmission(ctx context.Context, arg ResubmitKYCSubmissionParams) (KycSubmission, error) {
	row := q.db.QueryRow(ctx, resubmitKYCSubmission,
		arg.BusinessType,
		arg.GhanaCardNumber,
		arg.SelfiePhotoPath,
		arg.BusinessRegNumber,
		arg.Tin,
		arg.EntityType,
		arg.RegistrationCertPath,
		arg.Notes,
		arg.ID,
	)
	var i KycSubmission
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.RequestedTier,
		&i.GhanaCardNumber,
		&i.BusinessRegNumber,
		&i.Notes,
		&i.Status,
		&i.ReviewerNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelfiePhotoPath,
		&i.BusinessType,
		&i.Tin,
		&i.EntityType,
		&i.RegistrationCertPath,
	)
	return i, err
}

const reviewKYCSubmission = `-- name: ReviewKYCSubmission :one
UPDATE kyc_submissions
SET status = $1, reviewer_notes = $2,
    reviewed_by = $3, reviewed_at = now()
WHERE id = $4
RETURNING id, merchant_id, requested_tier, ghana_card_number, business_reg_number, notes, status, reviewer_notes, reviewed_by, reviewed_at, created_at, updated_at, selfie_photo_path, business_type, tin, entity_type, registration_cert_path
`

type ReviewKYCSubmissionParams struct {
	Status        string      `json:"status"`
	ReviewerNotes pgtype.Text `json:"reviewer_notes"`
	ReviewedBy    pgtype.UUID `json:"reviewed_by"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) ReviewKYCSubmission(ctx context.Context, arg ReviewKYCSubmissionParams) (KycSubmission, error) {
	row := q.db.QueryRow(ctx, reviewKYCSubmission,
		arg.Status,
		arg.ReviewerNotes,
		arg.ReviewedBy,
		arg.ID,
	)
	var i KycSubmission
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.RequestedTier,
		&i.GhanaCardNumber,
		&i.BusinessRegNumber,
		&i.Notes,
		&i.Status,
		&i.ReviewerNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelfiePhotoPath,
		&i.BusinessType,
		&i.Tin,
		&i.EntityType,
		&i.RegistrationCertPath,
	)
	return i, err
}
