// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: kyc_tier_limits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getKYCTierLimit = `-- name: GetKYCTierLimit :one
SELECT tier, per_transaction_pesewas, daily_pesewas, cumulative_pesewas, updated_at FROM kyc_tier_limits WHERE tier = $1
`

func (q *Queries) GetKYCTierLimit(ctx context.Context, tier int16) (KycTierLimit, error) {
	row := q.db.QueryRow(ctx, getKYCTierLimit, tier)
	var i KycTierLimit
	err := row.Scan(
		&i.Tier,
		&i.PerTransactionPesewas,
		&i.DailyPesewas,
		&i.CumulativePesewas,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantVolume = `-- name: GetMerchantVolume :one
SELECT
  COALESCE(SUM(p.amount_pesewas) FILTER (
    WHERE p.paid_at >= date_trunc('day', now())
  ), 0)::bigint AS today_pesewas,
  COALESCE(SUM(p.amount_pesewas), 0)::bigint AS cumulative_pesewas
FROM payments p
JOIN invoices i ON i.id = p.invoice_id
WHERE i.merchant_id = $1 AND p.status = 'success'
`

type GetMerchantVolumeRow struct {
	TodayPesewas      int64 `json:"today_pesewas"`
	CumulativePesewas int64 `json:"cumulative_pesewas"`
}

// Collected volume for limit checks, measured on successful payments rather
// than invoice totals: an invoice that was raised but never paid moved no
// money and must not consume a merchant's headroom.
//
// Deliberately gross, not net of refunds — otherwise a merchant could
// refund their way back under a cap and transact the same money twice. The
// daily window is a plain UTC calendar day, which is Ghana local time
// year-round (UTC+0, no DST).
func (q *Queries) GetMerchantVolume(ctx context.Context, merchantID pgtype.UUID) (GetMerchantVolumeRow, error) {
	row := q.db.QueryRow(ctx, getMerchantVolume, merchantID)
	var i GetMerchantVolumeRow
	err := row.Scan(&i.TodayPesewas, &i.CumulativePesewas)
	return i, err
}

const listKYCTierLimits = `-- name: ListKYCTierLimits :many
SELECT tier, per_transaction_pesewas, daily_pesewas, cumulative_pesewas, updated_at FROM kyc_tier_limits ORDER BY tier
`

func (q *Queries) ListKYCTierLimits(ctx context.Context) ([]KycTierLimit, error) {
	rows, err := q.db.Query(ctx, listKYCTierLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KycTierLimit{}
	for rows.Next() {
		var i KycTierLimit
		if err := rows.Scan(
			&i.Tier,
			&i.PerTransactionPesewas,
			&i.DailyPesewas,
			&i.CumulativePesewas,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKYCTierLimit = `-- name: UpdateKYCTierLimit :one
UPDATE kyc_tier_limits
SET per_transaction_pesewas = $1,
    daily_pesewas = $2,
    cumulative_pesewas = $3
WHERE tier = $4
RETURNING tier, per_transaction_pesewas, daily_pesewas, cumulative_pesewas, updated_at
`

type UpdateKYCTierLimitParams struct {
	PerTransactionPesewas pgtype.Int8 `json:"per_transaction_pesewas"`
	DailyPesewas          pgtype.Int8 `json:"daily_pesewas"`
	CumulativePesewas     pgtype.Int8 `json:"cumulative_pesewas"`
	Tier                  int16       `json:"tier"`
}

// NULL on any column means "no cap" — the enforcement path skips an unset
// limit rather than treating it as zero.
func (q *Queries) UpdateKYCTierLimit(ctx context.Context, arg UpdateKYCTierLimitParams) (KycTierLimit, error) {
	row := q.db.QueryRow(ctx, updateKYCTierLimit,
		arg.PerTransactionPesewas,
		arg.DailyPesewas,
		arg.CumulativePesewas,
		arg.Tier,
	)
	var i KycTierLimit
	err := row.Scan(
		&i.Tier,
		&i.PerTransactionPesewas,
		&i.DailyPesewas,
		&i.CumulativePesewas,
		&i.UpdatedAt,
	)
	return i, err
}
