// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: menus.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMenu = `-- name: CreateMenu :one
INSERT INTO menus (parent_id, permission_id, label, path, icon, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, parent_id, permission_id, label, path, icon, sort_order, created_at, updated_at
`

type CreateMenuParams struct {
	ParentID     pgtype.UUID `json:"parent_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
	Label        string      `json:"label"`
	Path         pgtype.Text `json:"path"`
	Icon         pgtype.Text `json:"icon"`
	SortOrder    int32       `json:"sort_order"`
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, createMenu,
		arg.ParentID,
		arg.PermissionID,
		arg.Label,
		arg.Path,
		arg.Icon,
		arg.SortOrder,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.PermissionID,
		&i.Label,
		&i.Path,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMenu = `-- name: DeleteMenu :exec
DELETE FROM menus WHERE id = $1
`

func (q *Queries) DeleteMenu(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenu, id)
	return err
}

const getMenu = `-- name: GetMenu :one
SELECT id, parent_id, permission_id, label, path, icon, sort_order, created_at, updated_at FROM menus WHERE id = $1
`

func (q *Queries) GetMenu(ctx context.Context, id pgtype.UUID) (Menu, error) {
	row := q.db.QueryRow(ctx, getMenu, id)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.PermissionID,
		&i.Label,
		&i.Path,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMenus = `-- name: ListMenus :many
SELECT id, parent_id, permission_id, label, path, icon, sort_order, created_at, updated_at FROM menus ORDER BY sort_order, label
`

func (q *Queries) ListMenus(ctx context.Context) ([]Menu, error) {
	rows, err := q.db.Query(ctx, listMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Menu{}
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.PermissionID,
			&i.Label,
			&i.Path,
			&i.Icon,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenusForUser = `-- name: ListMenusForUser :many
WITH RECURSIVE granted AS (
  SELECT m.id, m.parent_id, m.permission_id, m.label, m.path, m.icon, m.sort_order, m.created_at, m.updated_at FROM menus m
  WHERE m.permission_id IS NULL
     OR m.permission_id IN (
       SELECT p.id FROM permissions p
       JOIN role_permissions rp ON rp.permission_id = p.id
       JOIN user_roles ur ON ur.role_id = rp.role_id
       WHERE ur.user_id = $1
       UNION
       SELECT p.id FROM permissions p
       JOIN user_permissions up ON up.permission_id = p.id
       WHERE up.user_id = $1
     )
), visible AS (
  SELECT id, parent_id, permission_id, label, path, icon, sort_order, created_at, updated_at FROM granted
  UNION
  SELECT m.id, m.parent_id, m.permission_id, m.label, m.path, m.icon, m.sort_order, m.created_at, m.updated_at FROM menus m
  JOIN visible v ON m.id = v.parent_id
)
SELECT id, parent_id, permission_id, label, path, icon, sort_order, created_at, updated_at FROM visible ORDER BY sort_order, label
`

type ListMenusForUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	Label        string             `json:"label"`
	Path         pgtype.Text        `json:"path"`
	Icon         pgtype.Text        `json:"icon"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// ListMenusForUser returns every menu with no permission requirement, every
// menu whose permission is among the caller's effective permissions (via
// role or direct grant), AND every ancestor of such a menu — otherwise a
// child could pass its own permission check while its parent doesn't,
// leaving it with no reachable parent in the assembled tree. This is what
// the Back Office sidebar calls.
func (q *Queries) ListMenusForUser(ctx context.Context, userID pgtype.UUID) ([]ListMenusForUserRow, error) {
	rows, err := q.db.Query(ctx, listMenusForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMenusForUserRow{}
	for rows.Next() {
		var i ListMenusForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.PermissionID,
			&i.Label,
			&i.Path,
			&i.Icon,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenu = `-- name: UpdateMenu :one
UPDATE menus
SET parent_id = $2, permission_id = $3, label = $4, path = $5, icon = $6, sort_order = $7
WHERE id = $1
RETURNING id, parent_id, permission_id, label, path, icon, sort_order, created_at, updated_at
`

type UpdateMenuParams struct {
	ID           pgtype.UUID `json:"id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
	Label        string      `json:"label"`
	Path         pgtype.Text `json:"path"`
	Icon         pgtype.Text `json:"icon"`
	SortOrder    int32       `json:"sort_order"`
}

func (q *Queries) UpdateMenu(ctx context.Context, arg UpdateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, updateMenu,
		arg.ID,
		arg.ParentID,
		arg.PermissionID,
		arg.Label,
		arg.Path,
		arg.Icon,
		arg.SortOrder,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.PermissionID,
		&i.Label,
		&i.Path,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
