// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: merchants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveMerchantKYC = `-- name: ApproveMerchantKYC :one
UPDATE merchants
SET kyc_tier = $1, business_type = $2
WHERE id = $3
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type ApproveMerchantKYCParams struct {
	KycTier      int16       `json:"kyc_tier"`
	BusinessType pgtype.Text `json:"business_type"`
	ID           pgtype.UUID `json:"id"`
}

// Used when a submission is approved: the tier and the fork that earned it
// land together, so a Tier 2 merchant always carries business_type
// 'registered' and the two can never drift apart.
func (q *Queries) ApproveMerchantKYC(ctx context.Context, arg ApproveMerchantKYCParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, approveMerchantKYC, arg.KycTier, arg.BusinessType, arg.ID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (business_name, category, phone, username, email, password_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type CreateMerchantParams struct {
	BusinessName string      `json:"business_name"`
	Category     pgtype.Text `json:"category"`
	Phone        string      `json:"phone"`
	Username     pgtype.Text `json:"username"`
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant,
		arg.BusinessName,
		arg.Category,
		arg.Phone,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code FROM merchants WHERE id = $1
`

func (q *Queries) GetMerchant(ctx context.Context, id pgtype.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchant, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const getMerchantByEmail = `-- name: GetMerchantByEmail :one
SELECT id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code FROM merchants WHERE email = $1::text
`

func (q *Queries) GetMerchantByEmail(ctx context.Context, dollar_1 string) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByEmail, dollar_1)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const getMerchantByPhone = `-- name: GetMerchantByPhone :one
SELECT id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code FROM merchants WHERE phone = $1
`

func (q *Queries) GetMerchantByPhone(ctx context.Context, phone string) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByPhone, phone)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const getMerchantByWhatsAppPhoneNumberID = `-- name: GetMerchantByWhatsAppPhoneNumberID :one
SELECT id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code FROM merchants WHERE whatsapp_phone_number_id = $1::text
`

// Attributes an inbound WhatsApp webhook to a merchant — see
// internal/whatsapp and handlers/whatsapp.go.
func (q *Queries) GetMerchantByWhatsAppPhoneNumberID(ctx context.Context, dollar_1 string) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByWhatsAppPhoneNumberID, dollar_1)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const incrementMerchantStorageUsed = `-- name: IncrementMerchantStorageUsed :one
UPDATE merchants SET storage_used_bytes = storage_used_bytes + $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type IncrementMerchantStorageUsedParams struct {
	ID               pgtype.UUID `json:"id"`
	StorageUsedBytes int64       `json:"storage_used_bytes"`
}

// Section 4.2: item photo uploads. delta is the file size in bytes — always
// positive today (nothing decrements it yet; replacing/archiving an item's
// photo leaves the old file's bytes counted, a known simplification for
// this first pass).
func (q *Queries) IncrementMerchantStorageUsed(ctx context.Context, arg IncrementMerchantStorageUsedParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, incrementMerchantStorageUsed, arg.ID, arg.StorageUsedBytes)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const listMerchants = `-- name: ListMerchants :many
SELECT id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code FROM merchants
WHERE ($3::text = '' OR status = $3::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMerchantsParams struct {
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	StatusFilter string `json:"status_filter"`
}

func (q *Queries) ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error) {
	rows, err := q.db.Query(ctx, listMerchants, arg.Limit, arg.Offset, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Merchant{}
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.BusinessName,
			&i.Category,
			&i.Phone,
			&i.KycTier,
			&i.Status,
			&i.ServiceChargeAllocation,
			&i.ServiceChargeSplitBps,
			&i.PayoutAccountType,
			&i.PayoutAccountRef,
			&i.PayoutSchedule,
			&i.PayoutMinThresholdPesewas,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WhatsappAutoReplyEnabled,
			&i.WhatsappGreetingMessage,
			&i.DeliveryEnabled,
			&i.Email,
			&i.PasswordHash,
			&i.Username,
			&i.EmailVerifiedAt,
			&i.WhatsappPhoneNumberID,
			&i.StorageUsedBytes,
			&i.WhatsappCatalogID,
			&i.BusinessType,
			&i.PayoutBankCode,
			&i.PayoutAccountName,
			&i.PayoutAccountVerifiedAt,
			&i.PaystackSubaccountCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMerchantDeliveryEnabled = `-- name: UpdateMerchantDeliveryEnabled :one
UPDATE merchants SET delivery_enabled = $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type UpdateMerchantDeliveryEnabledParams struct {
	ID              pgtype.UUID `json:"id"`
	DeliveryEnabled bool        `json:"delivery_enabled"`
}

func (q *Queries) UpdateMerchantDeliveryEnabled(ctx context.Context, arg UpdateMerchantDeliveryEnabledParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantDeliveryEnabled, arg.ID, arg.DeliveryEnabled)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const updateMerchantEmail = `-- name: UpdateMerchantEmail :one
UPDATE merchants SET email = $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type UpdateMerchantEmailParams struct {
	ID    pgtype.UUID `json:"id"`
	Email pgtype.Text `json:"email"`
}

func (q *Queries) UpdateMerchantEmail(ctx context.Context, arg UpdateMerchantEmailParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantEmail, arg.ID, arg.Email)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const updateMerchantFeeSettings = `-- name: UpdateMerchantFeeSettings :one
UPDATE merchants
SET service_charge_allocation = $2,
    service_charge_split_bps = $3
WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type UpdateMerchantFeeSettingsParams struct {
	ID                      pgtype.UUID `json:"id"`
	ServiceChargeAllocation string      `json:"service_charge_allocation"`
	ServiceChargeSplitBps   pgtype.Int4 `json:"service_charge_split_bps"`
}

func (q *Queries) UpdateMerchantFeeSettings(ctx context.Context, arg UpdateMerchantFeeSettingsParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantFeeSettings, arg.ID, arg.ServiceChargeAllocation, arg.ServiceChargeSplitBps)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const updateMerchantKYCTier = `-- name: UpdateMerchantKYCTier :one
UPDATE merchants SET kyc_tier = $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type UpdateMerchantKYCTierParams struct {
	ID      pgtype.UUID `json:"id"`
	KycTier int16       `json:"kyc_tier"`
}

// Used by the Back Office tier override, which moves the tier without a
// submission behind it and so leaves business_type alone.
func (q *Queries) UpdateMerchantKYCTier(ctx context.Context, arg UpdateMerchantKYCTierParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantKYCTier, arg.ID, arg.KycTier)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const updateMerchantPayoutAccount = `-- name: UpdateMerchantPayoutAccount :one
UPDATE merchants
SET payout_account_type = $1,
    payout_account_ref = $2,
    payout_bank_code = $3,
    payout_account_name = $4,
    payout_account_verified_at = $5
WHERE id = $6
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type UpdateMerchantPayoutAccountParams struct {
	PayoutAccountType       pgtype.Text        `json:"payout_account_type"`
	PayoutAccountRef        pgtype.Text        `json:"payout_account_ref"`
	PayoutBankCode          pgtype.Text        `json:"payout_bank_code"`
	PayoutAccountName       pgtype.Text        `json:"payout_account_name"`
	PayoutAccountVerifiedAt pgtype.Timestamptz `json:"payout_account_verified_at"`
	ID                      pgtype.UUID        `json:"id"`
}

// account_name and verified_at travel together with the account details
// they describe — never set independently, so a resolved name can never
// outlive the account number it was resolved against. See
// UpdateMerchantPayoutAccountParams' caller (SetPayoutAccount) for the
// rule that clears them back to null whenever the account itself changes.
func (q *Queries) UpdateMerchantPayoutAccount(ctx context.Context, arg UpdateMerchantPayoutAccountParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantPayoutAccount,
		arg.PayoutAccountType,
		arg.PayoutAccountRef,
		arg.PayoutBankCode,
		arg.PayoutAccountName,
		arg.PayoutAccountVerifiedAt,
		arg.ID,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const updateMerchantStatus = `-- name: UpdateMerchantStatus :one
UPDATE merchants SET status = $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type UpdateMerchantStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantStatus, arg.ID, arg.Status)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const updateMerchantSubaccountCode = `-- name: UpdateMerchantSubaccountCode :one
UPDATE merchants SET paystack_subaccount_code = $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type UpdateMerchantSubaccountCodeParams struct {
	ID                     pgtype.UUID `json:"id"`
	PaystackSubaccountCode pgtype.Text `json:"paystack_subaccount_code"`
}

// Provisioning-only: records the Paystack subaccount created/updated
// alongside a verified payout account (SetPayoutAccount in
// payout_account.go). Never changes how any payment routes by itself —
// see InitiateCheckoutPayment for the only place that reads this and
// actually splits a charge.
func (q *Queries) UpdateMerchantSubaccountCode(ctx context.Context, arg UpdateMerchantSubaccountCodeParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantSubaccountCode, arg.ID, arg.PaystackSubaccountCode)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const updateMerchantWhatsAppCatalogID = `-- name: UpdateMerchantWhatsAppCatalogID :one
UPDATE merchants SET whatsapp_catalog_id = $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type UpdateMerchantWhatsAppCatalogIDParams struct {
	ID                pgtype.UUID `json:"id"`
	WhatsappCatalogID pgtype.Text `json:"whatsapp_catalog_id"`
}

// Admin-only provisioning step (Section 6.2), same reasoning as
// UpdateMerchantWhatsAppPhoneNumberID: an admin creates the catalog in
// Meta Commerce Manager and connects it to the merchant's WhatsApp
// Business Account, then records the resulting catalog_id here — no
// merchant self-service path exists for this.
func (q *Queries) UpdateMerchantWhatsAppCatalogID(ctx context.Context, arg UpdateMerchantWhatsAppCatalogIDParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantWhatsAppCatalogID, arg.ID, arg.WhatsappCatalogID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const updateMerchantWhatsAppPhoneNumberID = `-- name: UpdateMerchantWhatsAppPhoneNumberID :one
UPDATE merchants SET whatsapp_phone_number_id = $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type UpdateMerchantWhatsAppPhoneNumberIDParams struct {
	ID                    pgtype.UUID `json:"id"`
	WhatsappPhoneNumberID pgtype.Text `json:"whatsapp_phone_number_id"`
}

// Admin-only provisioning step (Section 7.3): OrderxPay registers the
// merchant's number under the platform WABA in Meta's console, then
// records the resulting phone_number_id here.
func (q *Queries) UpdateMerchantWhatsAppPhoneNumberID(ctx context.Context, arg UpdateMerchantWhatsAppPhoneNumberIDParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantWhatsAppPhoneNumberID, arg.ID, arg.WhatsappPhoneNumberID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}

const updateMerchantWhatsAppSettings = `-- name: UpdateMerchantWhatsAppSettings :one
UPDATE merchants
SET whatsapp_auto_reply_enabled = $2,
    whatsapp_greeting_message = $3
WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes, whatsapp_catalog_id, business_type, payout_bank_code, payout_account_name, payout_account_verified_at, paystack_subaccount_code
`

type UpdateMerchantWhatsAppSettingsParams struct {
	ID                       pgtype.UUID `json:"id"`
	WhatsappAutoReplyEnabled bool        `json:"whatsapp_auto_reply_enabled"`
	WhatsappGreetingMessage  pgtype.Text `json:"whatsapp_greeting_message"`
}

func (q *Queries) UpdateMerchantWhatsAppSettings(ctx context.Context, arg UpdateMerchantWhatsAppSettingsParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantWhatsAppSettings, arg.ID, arg.WhatsappAutoReplyEnabled, arg.WhatsappGreetingMessage)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
		&i.WhatsappCatalogID,
		&i.BusinessType,
		&i.PayoutBankCode,
		&i.PayoutAccountName,
		&i.PayoutAccountVerifiedAt,
		&i.PaystackSubaccountCode,
	)
	return i, err
}
