// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: merchant_notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMerchantNote = `-- name: CreateMerchantNote :one
INSERT INTO merchant_notes (merchant_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, merchant_id, author_id, body, created_at
`

type CreateMerchantNoteParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	AuthorID   pgtype.UUID `json:"author_id"`
	Body       string      `json:"body"`
}

func (q *Queries) CreateMerchantNote(ctx context.Context, arg CreateMerchantNoteParams) (MerchantNote, error) {
	row := q.db.QueryRow(ctx, createMerchantNote, arg.MerchantID, arg.AuthorID, arg.Body)
	var i MerchantNote
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listMerchantNotes = `-- name: ListMerchantNotes :many
SELECT n.id, n.merchant_id, n.author_id, n.body, n.created_at, u.name AS author_name
FROM merchant_notes n
JOIN users u ON u.id = n.author_id
WHERE n.merchant_id = $1
ORDER BY n.created_at DESC
`

type ListMerchantNotesRow struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	Body       string             `json:"body"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AuthorName string             `json:"author_name"`
}

func (q *Queries) ListMerchantNotes(ctx context.Context, merchantID pgtype.UUID) ([]ListMerchantNotesRow, error) {
	rows, err := q.db.Query(ctx, listMerchantNotes, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantNotesRow{}
	for rows.Next() {
		var i ListMerchantNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
