// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: merchant_locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultMerchantLocation = `-- name: ClearDefaultMerchantLocation :exec
UPDATE merchant_locations SET is_default = false WHERE merchant_id = $1 AND is_default
`

// Step 1 of "set this location as default" — unset whatever the current
// default is first so the partial unique index (merchant_id) WHERE
// is_default never sees two defaults at once, even transiently.
func (q *Queries) ClearDefaultMerchantLocation(ctx context.Context, merchantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultMerchantLocation, merchantID)
	return err
}

const createMerchantLocation = `-- name: CreateMerchantLocation :one
INSERT INTO merchant_locations (merchant_id, label, address, phone, is_default, lat, lng)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, label, address, phone, is_default, status, created_at, updated_at, lat, lng
`

type CreateMerchantLocationParams struct {
	MerchantID pgtype.UUID   `json:"merchant_id"`
	Label      string        `json:"label"`
	Address    string        `json:"address"`
	Phone      pgtype.Text   `json:"phone"`
	IsDefault  bool          `json:"is_default"`
	Lat        pgtype.Float8 `json:"lat"`
	Lng        pgtype.Float8 `json:"lng"`
}

func (q *Queries) CreateMerchantLocation(ctx context.Context, arg CreateMerchantLocationParams) (MerchantLocation, error) {
	row := q.db.QueryRow(ctx, createMerchantLocation,
		arg.MerchantID,
		arg.Label,
		arg.Address,
		arg.Phone,
		arg.IsDefault,
		arg.Lat,
		arg.Lng,
	)
	var i MerchantLocation
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Label,
		&i.Address,
		&i.Phone,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getMerchantLocation = `-- name: GetMerchantLocation :one
SELECT id, merchant_id, label, address, phone, is_default, status, created_at, updated_at, lat, lng FROM merchant_locations WHERE id = $1
`

func (q *Queries) GetMerchantLocation(ctx context.Context, id pgtype.UUID) (MerchantLocation, error) {
	row := q.db.QueryRow(ctx, getMerchantLocation, id)
	var i MerchantLocation
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Label,
		&i.Address,
		&i.Phone,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const listMerchantLocationsByMerchant = `-- name: ListMerchantLocationsByMerchant :many
SELECT id, merchant_id, label, address, phone, is_default, status, created_at, updated_at, lat, lng FROM merchant_locations
WHERE merchant_id = $1 AND status = 'active'
ORDER BY is_default DESC, created_at
`

func (q *Queries) ListMerchantLocationsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]MerchantLocation, error) {
	rows, err := q.db.Query(ctx, listMerchantLocationsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantLocation{}
	for rows.Next() {
		var i MerchantLocation
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Label,
			&i.Address,
			&i.Phone,
			&i.IsDefault,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultMerchantLocation = `-- name: SetDefaultMerchantLocation :execrows
UPDATE merchant_locations SET is_default = true WHERE id = $1 AND merchant_id = $2
`

type SetDefaultMerchantLocationParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) SetDefaultMerchantLocation(ctx context.Context, arg SetDefaultMerchantLocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDefaultMerchantLocation, arg.ID, arg.MerchantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMerchantLocation = `-- name: UpdateMerchantLocation :execrows
UPDATE merchant_locations
SET label = $2,
    address = $3,
    phone = $4,
    status = $5,
    lat = $6,
    lng = $7
WHERE id = $1 AND merchant_id = $8
`

type UpdateMerchantLocationParams struct {
	ID         pgtype.UUID   `json:"id"`
	Label      string        `json:"label"`
	Address    string        `json:"address"`
	Phone      pgtype.Text   `json:"phone"`
	Status     string        `json:"status"`
	Lat        pgtype.Float8 `json:"lat"`
	Lng        pgtype.Float8 `json:"lng"`
	MerchantID pgtype.UUID   `json:"merchant_id"`
}

// Ownership enforced in the WHERE clause, same pattern as
// UpdateDeliveryOption — the route path only carries the location's own
// id, not the merchant id.
func (q *Queries) UpdateMerchantLocation(ctx context.Context, arg UpdateMerchantLocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMerchantLocation,
		arg.ID,
		arg.Label,
		arg.Address,
		arg.Phone,
		arg.Status,
		arg.Lat,
		arg.Lng,
		arg.MerchantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
