// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: merchants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (business_name, category, phone, username, email, password_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes
`

type CreateMerchantParams struct {
	BusinessName string      `json:"business_name"`
	Category     pgtype.Text `json:"category"`
	Phone        string      `json:"phone"`
	Username     pgtype.Text `json:"username"`
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant,
		arg.BusinessName,
		arg.Category,
		arg.Phone,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
	)
	return i, err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes FROM merchants WHERE id = $1
`

func (q *Queries) GetMerchant(ctx context.Context, id pgtype.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchant, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
	)
	return i, err
}

const getMerchantByEmail = `-- name: GetMerchantByEmail :one
SELECT id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes FROM merchants WHERE email = $1::text
`

func (q *Queries) GetMerchantByEmail(ctx context.Context, dollar_1 string) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByEmail, dollar_1)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
	)
	return i, err
}

const getMerchantByPhone = `-- name: GetMerchantByPhone :one
SELECT id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes FROM merchants WHERE phone = $1
`

func (q *Queries) GetMerchantByPhone(ctx context.Context, phone string) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByPhone, phone)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
	)
	return i, err
}

const getMerchantByWhatsAppPhoneNumberID = `-- name: GetMerchantByWhatsAppPhoneNumberID :one
SELECT id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes FROM merchants WHERE whatsapp_phone_number_id = $1::text
`

// Attributes an inbound WhatsApp webhook to a merchant — see
// internal/whatsapp and handlers/whatsapp.go.
func (q *Queries) GetMerchantByWhatsAppPhoneNumberID(ctx context.Context, dollar_1 string) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByWhatsAppPhoneNumberID, dollar_1)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
	)
	return i, err
}

const incrementMerchantStorageUsed = `-- name: IncrementMerchantStorageUsed :one
UPDATE merchants SET storage_used_bytes = storage_used_bytes + $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes
`

type IncrementMerchantStorageUsedParams struct {
	ID               pgtype.UUID `json:"id"`
	StorageUsedBytes int64       `json:"storage_used_bytes"`
}

// Section 4.2: item photo uploads. delta is the file size in bytes — always
// positive today (nothing decrements it yet; replacing/archiving an item's
// photo leaves the old file's bytes counted, a known simplification for
// this first pass).
func (q *Queries) IncrementMerchantStorageUsed(ctx context.Context, arg IncrementMerchantStorageUsedParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, incrementMerchantStorageUsed, arg.ID, arg.StorageUsedBytes)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
	)
	return i, err
}

const listMerchants = `-- name: ListMerchants :many
SELECT id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes FROM merchants
WHERE ($3::text = '' OR status = $3::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMerchantsParams struct {
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	StatusFilter string `json:"status_filter"`
}

func (q *Queries) ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error) {
	rows, err := q.db.Query(ctx, listMerchants, arg.Limit, arg.Offset, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Merchant{}
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.BusinessName,
			&i.Category,
			&i.Phone,
			&i.KycTier,
			&i.Status,
			&i.ServiceChargeAllocation,
			&i.ServiceChargeSplitBps,
			&i.PayoutAccountType,
			&i.PayoutAccountRef,
			&i.PayoutSchedule,
			&i.PayoutMinThresholdPesewas,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PayoutFeeAbsorption,
			&i.WhatsappAutoReplyEnabled,
			&i.WhatsappGreetingMessage,
			&i.DeliveryEnabled,
			&i.Email,
			&i.PasswordHash,
			&i.Username,
			&i.EmailVerifiedAt,
			&i.WhatsappPhoneNumberID,
			&i.StorageUsedBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMerchantDeliveryEnabled = `-- name: UpdateMerchantDeliveryEnabled :one
UPDATE merchants SET delivery_enabled = $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes
`

type UpdateMerchantDeliveryEnabledParams struct {
	ID              pgtype.UUID `json:"id"`
	DeliveryEnabled bool        `json:"delivery_enabled"`
}

func (q *Queries) UpdateMerchantDeliveryEnabled(ctx context.Context, arg UpdateMerchantDeliveryEnabledParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantDeliveryEnabled, arg.ID, arg.DeliveryEnabled)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
	)
	return i, err
}

const updateMerchantFeeSettings = `-- name: UpdateMerchantFeeSettings :one
UPDATE merchants
SET service_charge_allocation = $2,
    service_charge_split_bps = $3,
    payout_fee_absorption = $4
WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes
`

type UpdateMerchantFeeSettingsParams struct {
	ID                      pgtype.UUID `json:"id"`
	ServiceChargeAllocation string      `json:"service_charge_allocation"`
	ServiceChargeSplitBps   pgtype.Int4 `json:"service_charge_split_bps"`
	PayoutFeeAbsorption     string      `json:"payout_fee_absorption"`
}

func (q *Queries) UpdateMerchantFeeSettings(ctx context.Context, arg UpdateMerchantFeeSettingsParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantFeeSettings,
		arg.ID,
		arg.ServiceChargeAllocation,
		arg.ServiceChargeSplitBps,
		arg.PayoutFeeAbsorption,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
	)
	return i, err
}

const updateMerchantKYCTier = `-- name: UpdateMerchantKYCTier :one
UPDATE merchants SET kyc_tier = $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes
`

type UpdateMerchantKYCTierParams struct {
	ID      pgtype.UUID `json:"id"`
	KycTier int16       `json:"kyc_tier"`
}

func (q *Queries) UpdateMerchantKYCTier(ctx context.Context, arg UpdateMerchantKYCTierParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantKYCTier, arg.ID, arg.KycTier)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
	)
	return i, err
}

const updateMerchantStatus = `-- name: UpdateMerchantStatus :one
UPDATE merchants SET status = $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes
`

type UpdateMerchantStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantStatus, arg.ID, arg.Status)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
	)
	return i, err
}

const updateMerchantWhatsAppPhoneNumberID = `-- name: UpdateMerchantWhatsAppPhoneNumberID :one
UPDATE merchants SET whatsapp_phone_number_id = $2 WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes
`

type UpdateMerchantWhatsAppPhoneNumberIDParams struct {
	ID                    pgtype.UUID `json:"id"`
	WhatsappPhoneNumberID pgtype.Text `json:"whatsapp_phone_number_id"`
}

// Admin-only provisioning step (Section 7.3): OrderxPay registers the
// merchant's number under the platform WABA in Meta's console, then
// records the resulting phone_number_id here.
func (q *Queries) UpdateMerchantWhatsAppPhoneNumberID(ctx context.Context, arg UpdateMerchantWhatsAppPhoneNumberIDParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantWhatsAppPhoneNumberID, arg.ID, arg.WhatsappPhoneNumberID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
	)
	return i, err
}

const updateMerchantWhatsAppSettings = `-- name: UpdateMerchantWhatsAppSettings :one
UPDATE merchants
SET whatsapp_auto_reply_enabled = $2,
    whatsapp_greeting_message = $3
WHERE id = $1
RETURNING id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption, whatsapp_auto_reply_enabled, whatsapp_greeting_message, delivery_enabled, email, password_hash, username, email_verified_at, whatsapp_phone_number_id, storage_used_bytes
`

type UpdateMerchantWhatsAppSettingsParams struct {
	ID                       pgtype.UUID `json:"id"`
	WhatsappAutoReplyEnabled bool        `json:"whatsapp_auto_reply_enabled"`
	WhatsappGreetingMessage  pgtype.Text `json:"whatsapp_greeting_message"`
}

func (q *Queries) UpdateMerchantWhatsAppSettings(ctx context.Context, arg UpdateMerchantWhatsAppSettingsParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantWhatsAppSettings, arg.ID, arg.WhatsappAutoReplyEnabled, arg.WhatsappGreetingMessage)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.Category,
		&i.Phone,
		&i.KycTier,
		&i.Status,
		&i.ServiceChargeAllocation,
		&i.ServiceChargeSplitBps,
		&i.PayoutAccountType,
		&i.PayoutAccountRef,
		&i.PayoutSchedule,
		&i.PayoutMinThresholdPesewas,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutFeeAbsorption,
		&i.WhatsappAutoReplyEnabled,
		&i.WhatsappGreetingMessage,
		&i.DeliveryEnabled,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.EmailVerifiedAt,
		&i.WhatsappPhoneNumberID,
		&i.StorageUsedBytes,
	)
	return i, err
}
