// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: merchant_analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMerchantBestSellingItems = `-- name: GetMerchantBestSellingItems :many

SELECT
  ili.description,
  SUM(ili.quantity)::bigint AS total_quantity,
  SUM(ili.line_total_pesewas)::bigint AS total_revenue_pesewas
FROM invoice_line_items ili
JOIN invoices i ON i.id = ili.invoice_id
WHERE i.merchant_id = $1
  AND i.status IN ('paid', 'partially_paid')
  AND i.created_at >= $2::timestamptz
  AND i.created_at < $3::timestamptz
GROUP BY ili.description
ORDER BY total_quantity DESC, total_revenue_pesewas DESC
LIMIT $4
`

type GetMerchantBestSellingItemsParams struct {
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	RowLimit    int32              `json:"row_limit"`
}

type GetMerchantBestSellingItemsRow struct {
	Description         string `json:"description"`
	TotalQuantity       int64  `json:"total_quantity"`
	TotalRevenuePesewas int64  `json:"total_revenue_pesewas"`
}

// Section 4.7: merchant-facing analytics + bookkeeping export. All queries
// are merchant-scoped (mounted under RequireOwnMerchant) and, unless noted,
// only count invoices that actually collected money (paid or
// partially_paid) within the requested period — a declined/expired invoice
// isn't a "sale".
func (q *Queries) GetMerchantBestSellingItems(ctx context.Context, arg GetMerchantBestSellingItemsParams) ([]GetMerchantBestSellingItemsRow, error) {
	rows, err := q.db.Query(ctx, getMerchantBestSellingItems,
		arg.MerchantID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMerchantBestSellingItemsRow{}
	for rows.Next() {
		var i GetMerchantBestSellingItemsRow
		if err := rows.Scan(&i.Description, &i.TotalQuantity, &i.TotalRevenuePesewas); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantDailyCollections = `-- name: GetMerchantDailyCollections :many
SELECT
  DATE(p.paid_at) AS day,
  COALESCE(SUM(p.amount_pesewas), 0)::bigint AS collected_pesewas,
  COUNT(p.id)::bigint AS payment_count
FROM payments p
JOIN invoices i ON i.id = p.invoice_id
WHERE i.merchant_id = $1
  AND p.status = 'success'
  AND p.paid_at >= $2::timestamptz
  AND p.paid_at < $3::timestamptz
GROUP BY DATE(p.paid_at)
ORDER BY day
`

type GetMerchantDailyCollectionsParams struct {
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type GetMerchantDailyCollectionsRow struct {
	Day              pgtype.Date `json:"day"`
	CollectedPesewas int64       `json:"collected_pesewas"`
	PaymentCount     int64       `json:"payment_count"`
}

// Grouped by actual payment date (not invoice date), matching the platform-
// wide GetDailyRevenue query in reporting.sql.
func (q *Queries) GetMerchantDailyCollections(ctx context.Context, arg GetMerchantDailyCollectionsParams) ([]GetMerchantDailyCollectionsRow, error) {
	rows, err := q.db.Query(ctx, getMerchantDailyCollections, arg.MerchantID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMerchantDailyCollectionsRow{}
	for rows.Next() {
		var i GetMerchantDailyCollectionsRow
		if err := rows.Scan(&i.Day, &i.CollectedPesewas, &i.PaymentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantOrderStats = `-- name: GetMerchantOrderStats :one
SELECT
  COUNT(*)::bigint AS order_count,
  COALESCE(AVG(total_pesewas), 0)::bigint AS average_order_value_pesewas,
  COALESCE(SUM(total_pesewas), 0)::bigint AS total_collected_pesewas,
  COUNT(DISTINCT customer_contact)::bigint AS unique_customer_count
FROM invoices
WHERE merchant_id = $1
  AND status IN ('paid', 'partially_paid')
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
`

type GetMerchantOrderStatsParams struct {
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type GetMerchantOrderStatsRow struct {
	OrderCount               int64 `json:"order_count"`
	AverageOrderValuePesewas int64 `json:"average_order_value_pesewas"`
	TotalCollectedPesewas    int64 `json:"total_collected_pesewas"`
	UniqueCustomerCount      int64 `json:"unique_customer_count"`
}

func (q *Queries) GetMerchantOrderStats(ctx context.Context, arg GetMerchantOrderStatsParams) (GetMerchantOrderStatsRow, error) {
	row := q.db.QueryRow(ctx, getMerchantOrderStats, arg.MerchantID, arg.PeriodStart, arg.PeriodEnd)
	var i GetMerchantOrderStatsRow
	err := row.Scan(
		&i.OrderCount,
		&i.AverageOrderValuePesewas,
		&i.TotalCollectedPesewas,
		&i.UniqueCustomerCount,
	)
	return i, err
}

const getMerchantRepeatCustomers = `-- name: GetMerchantRepeatCustomers :many
SELECT
  customer_contact,
  COUNT(*)::bigint AS order_count,
  COALESCE(SUM(total_pesewas), 0)::bigint AS total_spent_pesewas
FROM invoices
WHERE merchant_id = $1
  AND status IN ('paid', 'partially_paid')
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
GROUP BY customer_contact
HAVING COUNT(*) > 1
ORDER BY order_count DESC, total_spent_pesewas DESC
LIMIT $4
`

type GetMerchantRepeatCustomersParams struct {
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	RowLimit    int32              `json:"row_limit"`
}

type GetMerchantRepeatCustomersRow struct {
	CustomerContact   string `json:"customer_contact"`
	OrderCount        int64  `json:"order_count"`
	TotalSpentPesewas int64  `json:"total_spent_pesewas"`
}

// A "repeat" customer placed more than one paid/partially-paid order in the
// period, identified by customer_contact since there's no customers table.
func (q *Queries) GetMerchantRepeatCustomers(ctx context.Context, arg GetMerchantRepeatCustomersParams) ([]GetMerchantRepeatCustomersRow, error) {
	rows, err := q.db.Query(ctx, getMerchantRepeatCustomers,
		arg.MerchantID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMerchantRepeatCustomersRow{}
	for rows.Next() {
		var i GetMerchantRepeatCustomersRow
		if err := rows.Scan(&i.CustomerContact, &i.OrderCount, &i.TotalSpentPesewas); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantInvoicesForExport = `-- name: ListMerchantInvoicesForExport :many
SELECT
  i.reference,
  i.customer_contact,
  i.created_at,
  i.status,
  COALESCE(items.items_summary, '') AS items_summary,
  i.total_pesewas AS amount_invoiced_pesewas,
  COALESCE(pay.amount_paid_pesewas, 0)::bigint AS amount_paid_pesewas,
  (i.total_pesewas - COALESCE(pay.amount_paid_pesewas, 0))::bigint AS outstanding_pesewas,
  COALESCE(pay.channel, '') AS channel
FROM invoices i
LEFT JOIN LATERAL (
  SELECT STRING_AGG(ili.description || ' x' || ili.quantity, '; ' ORDER BY ili.id) AS items_summary
  FROM invoice_line_items ili WHERE ili.invoice_id = i.id
) items ON true
LEFT JOIN LATERAL (
  SELECT
    COALESCE(SUM(p.amount_pesewas), 0)::bigint AS amount_paid_pesewas,
    STRING_AGG(DISTINCT p.method, ', ') AS channel
  FROM payments p WHERE p.invoice_id = i.id AND p.status = 'success'
) pay ON true
WHERE i.merchant_id = $1
  AND i.created_at >= $2::timestamptz
  AND i.created_at < $3::timestamptz
ORDER BY i.created_at DESC
`

type ListMerchantInvoicesForExportParams struct {
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type ListMerchantInvoicesForExportRow struct {
	Reference             string             `json:"reference"`
	CustomerContact       string             `json:"customer_contact"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	Status                string             `json:"status"`
	ItemsSummary          []byte             `json:"items_summary"`
	AmountInvoicedPesewas int64              `json:"amount_invoiced_pesewas"`
	AmountPaidPesewas     int64              `json:"amount_paid_pesewas"`
	OutstandingPesewas    int64              `json:"outstanding_pesewas"`
	Channel               []byte             `json:"channel"`
}

// Backs the CSV bookkeeping export — every invoice in the period regardless
// of status (an accountant needs to see declined/expired ones too), with
// items and the payment method(s) used summarized per row.
func (q *Queries) ListMerchantInvoicesForExport(ctx context.Context, arg ListMerchantInvoicesForExportParams) ([]ListMerchantInvoicesForExportRow, error) {
	rows, err := q.db.Query(ctx, listMerchantInvoicesForExport, arg.MerchantID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantInvoicesForExportRow{}
	for rows.Next() {
		var i ListMerchantInvoicesForExportRow
		if err := rows.Scan(
			&i.Reference,
			&i.CustomerContact,
			&i.CreatedAt,
			&i.Status,
			&i.ItemsSummary,
			&i.AmountInvoicedPesewas,
			&i.AmountPaidPesewas,
			&i.OutstandingPesewas,
			&i.Channel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
