// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLogEntry struct {
	ID           pgtype.UUID        `json:"id"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ActorType    string             `json:"actor_type"`
	Action       string             `json:"action"`
	TargetEntity string             `json:"target_entity"`
	TargetID     pgtype.UUID        `json:"target_id"`
	BeforeState  []byte             `json:"before_state"`
	AfterState   []byte             `json:"after_state"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID              pgtype.UUID        `json:"id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CustomerContact string             `json:"customer_contact"`
	Channel         string             `json:"channel"`
	Direction       string             `json:"direction"`
	MessageType     string             `json:"message_type"`
	TemplateID      pgtype.Text        `json:"template_id"`
	Consent         bool               `json:"consent"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DeliveryOption struct {
	ID                 pgtype.UUID        `json:"id"`
	MerchantID         pgtype.UUID        `json:"merchant_id"`
	Type               string             `json:"type"`
	ContactName        pgtype.Text        `json:"contact_name"`
	ContactPhone       pgtype.Text        `json:"contact_phone"`
	ProviderKey        pgtype.Text        `json:"provider_key"`
	DeepLinkTemplate   pgtype.Text        `json:"deep_link_template"`
	FeeHandlingDefault string             `json:"fee_handling_default"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type FeeRule struct {
	ID             pgtype.UUID        `json:"id"`
	MerchantID     pgtype.UUID        `json:"merchant_id"`
	CommissionBps  int32              `json:"commission_bps"`
	AllocationType string             `json:"allocation_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Invoice struct {
	ID                      pgtype.UUID        `json:"id"`
	MerchantID              pgtype.UUID        `json:"merchant_id"`
	OrderRequestID          pgtype.UUID        `json:"order_request_id"`
	Reference               string             `json:"reference"`
	CustomerContact         string             `json:"customer_contact"`
	SubtotalPesewas         int64              `json:"subtotal_pesewas"`
	ServiceChargePesewas    int64              `json:"service_charge_pesewas"`
	ServiceChargeAllocation string             `json:"service_charge_allocation"`
	TotalPesewas            int64              `json:"total_pesewas"`
	Status                  string             `json:"status"`
	DeliveryOptionID        pgtype.UUID        `json:"delivery_option_id"`
	DeliveryAddress         pgtype.Text        `json:"delivery_address"`
	DeliveryFeeHandling     pgtype.Text        `json:"delivery_fee_handling"`
	DeliveryFeePesewas      pgtype.Int8        `json:"delivery_fee_pesewas"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	CommissionPesewas       int64              `json:"commission_pesewas"`
}

type InvoiceLineItem struct {
	ID               pgtype.UUID `json:"id"`
	InvoiceID        pgtype.UUID `json:"invoice_id"`
	ItemID           pgtype.UUID `json:"item_id"`
	Description      string      `json:"description"`
	UnitPricePesewas int64       `json:"unit_price_pesewas"`
	Quantity         int32       `json:"quantity"`
	LineTotalPesewas int64       `json:"line_total_pesewas"`
}

type Item struct {
	ID                 pgtype.UUID        `json:"id"`
	MerchantID         pgtype.UUID        `json:"merchant_id"`
	Name               string             `json:"name"`
	UnitPricePesewas   int64              `json:"unit_price_pesewas"`
	QtyUnit            pgtype.Text        `json:"qty_unit"`
	ImageUrl           pgtype.Text        `json:"image_url"`
	AvailabilityStatus string             `json:"availability_status"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type KycSubmission struct {
	ID                pgtype.UUID        `json:"id"`
	MerchantID        pgtype.UUID        `json:"merchant_id"`
	RequestedTier     int16              `json:"requested_tier"`
	GhanaCardNumber   string             `json:"ghana_card_number"`
	BusinessRegNumber pgtype.Text        `json:"business_reg_number"`
	Notes             pgtype.Text        `json:"notes"`
	Status            string             `json:"status"`
	ReviewerNotes     pgtype.Text        `json:"reviewer_notes"`
	ReviewedBy        pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Menu struct {
	ID           pgtype.UUID        `json:"id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	Label        string             `json:"label"`
	Path         pgtype.Text        `json:"path"`
	Icon         pgtype.Text        `json:"icon"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Merchant struct {
	ID                        pgtype.UUID        `json:"id"`
	BusinessName              string             `json:"business_name"`
	Category                  pgtype.Text        `json:"category"`
	Phone                     string             `json:"phone"`
	KycTier                   int16              `json:"kyc_tier"`
	Status                    string             `json:"status"`
	ServiceChargeAllocation   string             `json:"service_charge_allocation"`
	ServiceChargeSplitBps     pgtype.Int4        `json:"service_charge_split_bps"`
	PayoutAccountType         pgtype.Text        `json:"payout_account_type"`
	PayoutAccountRef          pgtype.Text        `json:"payout_account_ref"`
	PayoutSchedule            string             `json:"payout_schedule"`
	PayoutMinThresholdPesewas int64              `json:"payout_min_threshold_pesewas"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type OrderRequest struct {
	ID              pgtype.UUID        `json:"id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CustomerContact string             `json:"customer_contact"`
	RequestedItems  []byte             `json:"requested_items"`
	Status          string             `json:"status"`
	DeclineReason   pgtype.Text        `json:"decline_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID            pgtype.UUID        `json:"id"`
	InvoiceID     pgtype.UUID        `json:"invoice_id"`
	PspReference  string             `json:"psp_reference"`
	Method        string             `json:"method"`
	AmountPesewas int64              `json:"amount_pesewas"`
	Status        string             `json:"status"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PspFeePesewas int64              `json:"psp_fee_pesewas"`
	SettlementID  pgtype.UUID        `json:"settlement_id"`
}

type Permission struct {
	ID                pgtype.UUID        `json:"id"`
	PermissionGroupID pgtype.UUID        `json:"permission_group_id"`
	Key               string             `json:"key"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type PermissionGroup struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID        `json:"role_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Settlement struct {
	ID                      pgtype.UUID        `json:"id"`
	MerchantID              pgtype.UUID        `json:"merchant_id"`
	PeriodStart             pgtype.Date        `json:"period_start"`
	PeriodEnd               pgtype.Date        `json:"period_end"`
	GrossCollectionsPesewas int64              `json:"gross_collections_pesewas"`
	PspFeesPesewas          int64              `json:"psp_fees_pesewas"`
	CommissionPesewas       int64              `json:"commission_pesewas"`
	NetPayoutPesewas        int64              `json:"net_payout_pesewas"`
	Status                  string             `json:"status"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Staff struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	Name       string             `json:"name"`
	Phone      string             `json:"phone"`
	Role       string             `json:"role"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserPermission struct {
	UserID       pgtype.UUID        `json:"user_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserRole struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
