// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLogEntry struct {
	ID           pgtype.UUID        `json:"id"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ActorType    string             `json:"actor_type"`
	Action       string             `json:"action"`
	TargetEntity string             `json:"target_entity"`
	TargetID     pgtype.UUID        `json:"target_id"`
	BeforeState  []byte             `json:"before_state"`
	AfterState   []byte             `json:"after_state"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID              pgtype.UUID        `json:"id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CustomerContact string             `json:"customer_contact"`
	Channel         string             `json:"channel"`
	Direction       string             `json:"direction"`
	MessageType     string             `json:"message_type"`
	TemplateID      pgtype.Text        `json:"template_id"`
	Consent         bool               `json:"consent"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DeliveryOption struct {
	ID                 pgtype.UUID        `json:"id"`
	MerchantID         pgtype.UUID        `json:"merchant_id"`
	Type               string             `json:"type"`
	ContactName        pgtype.Text        `json:"contact_name"`
	ContactPhone       pgtype.Text        `json:"contact_phone"`
	ProviderKey        pgtype.Text        `json:"provider_key"`
	DeepLinkTemplate   pgtype.Text        `json:"deep_link_template"`
	FeeHandlingDefault string             `json:"fee_handling_default"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	FlatFeePesewas     pgtype.Int8        `json:"flat_fee_pesewas"`
	ServiceZone        pgtype.Text        `json:"service_zone"`
}

type DeliveryProvider struct {
	ID               pgtype.UUID        `json:"id"`
	Key              string             `json:"key"`
	Name             string             `json:"name"`
	DeepLinkTemplate string             `json:"deep_link_template"`
	Status           string             `json:"status"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Dispute struct {
	ID                  pgtype.UUID        `json:"id"`
	InvoiceID           pgtype.UUID        `json:"invoice_id"`
	ReasonCategory      string             `json:"reason_category"`
	Description         pgtype.Text        `json:"description"`
	Status              string             `json:"status"`
	ResolutionNotes     pgtype.Text        `json:"resolution_notes"`
	RefundPaymentID     pgtype.UUID        `json:"refund_payment_id"`
	RefundAmountPesewas pgtype.Int8        `json:"refund_amount_pesewas"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	ResolvedBy          pgtype.UUID        `json:"resolved_by"`
	ResolvedAt          pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type EmailVerification struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	Token      string             `json:"token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	UsedAt     pgtype.Timestamptz `json:"used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type FeatureFlag struct {
	ID              pgtype.UUID        `json:"id"`
	Key             string             `json:"key"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	EnabledGlobally bool               `json:"enabled_globally"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type FeatureFlagMerchant struct {
	FeatureFlagID pgtype.UUID        `json:"feature_flag_id"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type FeeRule struct {
	ID               pgtype.UUID        `json:"id"`
	MerchantID       pgtype.UUID        `json:"merchant_id"`
	CommissionBps    int32              `json:"commission_bps"`
	AllocationType   string             `json:"allocation_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CollectionFeeBps int32              `json:"collection_fee_bps"`
	PayoutFeeBps     int32              `json:"payout_fee_bps"`
	MarginBps        int32              `json:"margin_bps"`
}

type Integration struct {
	ID              pgtype.UUID        `json:"id"`
	ProviderKey     string             `json:"provider_key"`
	Category        string             `json:"category"`
	Built           bool               `json:"built"`
	SecretValue     pgtype.Text        `json:"secret_value"`
	SecretUpdatedAt pgtype.Timestamptz `json:"secret_updated_at"`
	SecretUpdatedBy pgtype.UUID        `json:"secret_updated_by"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Invoice struct {
	ID                      pgtype.UUID        `json:"id"`
	MerchantID              pgtype.UUID        `json:"merchant_id"`
	OrderRequestID          pgtype.UUID        `json:"order_request_id"`
	Reference               string             `json:"reference"`
	CustomerContact         string             `json:"customer_contact"`
	SubtotalPesewas         int64              `json:"subtotal_pesewas"`
	ServiceChargePesewas    int64              `json:"service_charge_pesewas"`
	ServiceChargeAllocation string             `json:"service_charge_allocation"`
	TotalPesewas            int64              `json:"total_pesewas"`
	Status                  string             `json:"status"`
	DeliveryOptionID        pgtype.UUID        `json:"delivery_option_id"`
	DeliveryAddress         pgtype.Text        `json:"delivery_address"`
	DeliveryFeeHandling     pgtype.Text        `json:"delivery_fee_handling"`
	DeliveryFeePesewas      pgtype.Int8        `json:"delivery_fee_pesewas"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	CommissionPesewas       int64              `json:"commission_pesewas"`
	PickupLocationID        pgtype.UUID        `json:"pickup_location_id"`
}

type InvoiceLineItem struct {
	ID               pgtype.UUID `json:"id"`
	InvoiceID        pgtype.UUID `json:"invoice_id"`
	ItemID           pgtype.UUID `json:"item_id"`
	Description      string      `json:"description"`
	UnitPricePesewas int64       `json:"unit_price_pesewas"`
	Quantity         int32       `json:"quantity"`
	LineTotalPesewas int64       `json:"line_total_pesewas"`
}

type Item struct {
	ID                 pgtype.UUID        `json:"id"`
	MerchantID         pgtype.UUID        `json:"merchant_id"`
	Name               string             `json:"name"`
	UnitPricePesewas   int64              `json:"unit_price_pesewas"`
	QtyUnit            pgtype.Text        `json:"qty_unit"`
	ImageUrl           pgtype.Text        `json:"image_url"`
	AvailabilityStatus string             `json:"availability_status"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type KycSubmission struct {
	ID                pgtype.UUID        `json:"id"`
	MerchantID        pgtype.UUID        `json:"merchant_id"`
	RequestedTier     int16              `json:"requested_tier"`
	GhanaCardNumber   string             `json:"ghana_card_number"`
	BusinessRegNumber pgtype.Text        `json:"business_reg_number"`
	Notes             pgtype.Text        `json:"notes"`
	Status            string             `json:"status"`
	ReviewerNotes     pgtype.Text        `json:"reviewer_notes"`
	ReviewedBy        pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Menu struct {
	ID           pgtype.UUID        `json:"id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	Label        string             `json:"label"`
	Path         pgtype.Text        `json:"path"`
	Icon         pgtype.Text        `json:"icon"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Merchant struct {
	ID                        pgtype.UUID        `json:"id"`
	BusinessName              string             `json:"business_name"`
	Category                  pgtype.Text        `json:"category"`
	Phone                     string             `json:"phone"`
	KycTier                   int16              `json:"kyc_tier"`
	Status                    string             `json:"status"`
	ServiceChargeAllocation   string             `json:"service_charge_allocation"`
	ServiceChargeSplitBps     pgtype.Int4        `json:"service_charge_split_bps"`
	PayoutAccountType         pgtype.Text        `json:"payout_account_type"`
	PayoutAccountRef          pgtype.Text        `json:"payout_account_ref"`
	PayoutSchedule            string             `json:"payout_schedule"`
	PayoutMinThresholdPesewas int64              `json:"payout_min_threshold_pesewas"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	PayoutFeeAbsorption       string             `json:"payout_fee_absorption"`
	WhatsappAutoReplyEnabled  bool               `json:"whatsapp_auto_reply_enabled"`
	WhatsappGreetingMessage   pgtype.Text        `json:"whatsapp_greeting_message"`
	DeliveryEnabled           bool               `json:"delivery_enabled"`
	Email                     pgtype.Text        `json:"email"`
	PasswordHash              pgtype.Text        `json:"password_hash"`
	Username                  pgtype.Text        `json:"username"`
	EmailVerifiedAt           pgtype.Timestamptz `json:"email_verified_at"`
	WhatsappPhoneNumberID     pgtype.Text        `json:"whatsapp_phone_number_id"`
	StorageUsedBytes          int64              `json:"storage_used_bytes"`
}

type MerchantLocation struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	Label      string             `json:"label"`
	Address    string             `json:"address"`
	Phone      pgtype.Text        `json:"phone"`
	IsDefault  bool               `json:"is_default"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type MerchantNote struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	Body       string             `json:"body"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID           pgtype.UUID        `json:"id"`
	MerchantID   pgtype.UUID        `json:"merchant_id"`
	Type         string             `json:"type"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	TargetEntity pgtype.Text        `json:"target_entity"`
	TargetID     pgtype.UUID        `json:"target_id"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type OrderRequest struct {
	ID              pgtype.UUID        `json:"id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CustomerContact string             `json:"customer_contact"`
	RequestedItems  []byte             `json:"requested_items"`
	Status          string             `json:"status"`
	DeclineReason   pgtype.Text        `json:"decline_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID                    pgtype.UUID        `json:"id"`
	InvoiceID             pgtype.UUID        `json:"invoice_id"`
	PspReference          string             `json:"psp_reference"`
	Method                string             `json:"method"`
	AmountPesewas         int64              `json:"amount_pesewas"`
	Status                string             `json:"status"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	PspFeePesewas         int64              `json:"psp_fee_pesewas"`
	SettlementID          pgtype.UUID        `json:"settlement_id"`
	RefundedAmountPesewas int64              `json:"refunded_amount_pesewas"`
}

type Permission struct {
	ID                pgtype.UUID        `json:"id"`
	PermissionGroupID pgtype.UUID        `json:"permission_group_id"`
	Key               string             `json:"key"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type PermissionGroup struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PhoneOtp struct {
	ID           pgtype.UUID        `json:"id"`
	Phone        string             `json:"phone"`
	Code         string             `json:"code"`
	AttemptCount int32              `json:"attempt_count"`
	VerifiedAt   pgtype.Timestamptz `json:"verified_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RiskFlag struct {
	ID              pgtype.UUID        `json:"id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	FlagType        string             `json:"flag_type"`
	DedupeKey       string             `json:"dedupe_key"`
	Details         string             `json:"details"`
	Status          string             `json:"status"`
	ResolutionNotes pgtype.Text        `json:"resolution_notes"`
	ReviewedBy      pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID        `json:"role_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Settlement struct {
	ID                      pgtype.UUID        `json:"id"`
	MerchantID              pgtype.UUID        `json:"merchant_id"`
	PeriodStart             pgtype.Date        `json:"period_start"`
	PeriodEnd               pgtype.Date        `json:"period_end"`
	GrossCollectionsPesewas int64              `json:"gross_collections_pesewas"`
	PspFeesPesewas          int64              `json:"psp_fees_pesewas"`
	CommissionPesewas       int64              `json:"commission_pesewas"`
	NetPayoutPesewas        int64              `json:"net_payout_pesewas"`
	Status                  string             `json:"status"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Staff struct {
	ID           pgtype.UUID        `json:"id"`
	MerchantID   pgtype.UUID        `json:"merchant_id"`
	Name         string             `json:"name"`
	Phone        string             `json:"phone"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserPermission struct {
	UserID       pgtype.UUID        `json:"user_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserRole struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WebhookDelivery struct {
	ID             pgtype.UUID        `json:"id"`
	Provider       string             `json:"provider"`
	EventType      pgtype.Text        `json:"event_type"`
	Reference      pgtype.Text        `json:"reference"`
	SignatureValid bool               `json:"signature_valid"`
	ProcessedOk    bool               `json:"processed_ok"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}
