// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE merchant_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, merchantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, merchantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (merchant_id, type, title, body, target_entity, target_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, merchant_id, type, title, body, target_entity, target_id, read_at, created_at
`

type CreateNotificationParams struct {
	MerchantID   pgtype.UUID `json:"merchant_id"`
	Type         string      `json:"type"`
	Title        string      `json:"title"`
	Body         string      `json:"body"`
	TargetEntity pgtype.Text `json:"target_entity"`
	TargetID     pgtype.UUID `json:"target_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.MerchantID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.TargetEntity,
		arg.TargetID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.TargetEntity,
		&i.TargetID,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByMerchant = `-- name: ListNotificationsByMerchant :many
SELECT id, merchant_id, type, title, body, target_entity, target_id, read_at, created_at FROM notifications
WHERE merchant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByMerchantParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListNotificationsByMerchant(ctx context.Context, arg ListNotificationsByMerchantParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.TargetEntity,
			&i.TargetID,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now()
WHERE merchant_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, merchantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, merchantID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = now()
WHERE id = $1 AND merchant_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.MerchantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
