// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: order_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderRequest = `-- name: CreateOrderRequest :one
INSERT INTO order_requests (merchant_id, customer_contact, customer_name, requested_items)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, customer_contact, requested_items, status, decline_reason, created_at, updated_at, customer_name, decline_reason_category
`

type CreateOrderRequestParams struct {
	MerchantID      pgtype.UUID `json:"merchant_id"`
	CustomerContact string      `json:"customer_contact"`
	CustomerName    pgtype.Text `json:"customer_name"`
	RequestedItems  []byte      `json:"requested_items"`
}

func (q *Queries) CreateOrderRequest(ctx context.Context, arg CreateOrderRequestParams) (OrderRequest, error) {
	row := q.db.QueryRow(ctx, createOrderRequest,
		arg.MerchantID,
		arg.CustomerContact,
		arg.CustomerName,
		arg.RequestedItems,
	)
	var i OrderRequest
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerContact,
		&i.RequestedItems,
		&i.Status,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.DeclineReasonCategory,
	)
	return i, err
}

const getOrderRequest = `-- name: GetOrderRequest :one
SELECT id, merchant_id, customer_contact, requested_items, status, decline_reason, created_at, updated_at, customer_name, decline_reason_category FROM order_requests WHERE id = $1
`

func (q *Queries) GetOrderRequest(ctx context.Context, id pgtype.UUID) (OrderRequest, error) {
	row := q.db.QueryRow(ctx, getOrderRequest, id)
	var i OrderRequest
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerContact,
		&i.RequestedItems,
		&i.Status,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.DeclineReasonCategory,
	)
	return i, err
}

const listPendingOrderRequestsByMerchant = `-- name: ListPendingOrderRequestsByMerchant :many
SELECT id, merchant_id, customer_contact, requested_items, status, decline_reason, created_at, updated_at, customer_name, decline_reason_category FROM order_requests
WHERE merchant_id = $1 AND status = 'pending'
ORDER BY created_at
`

func (q *Queries) ListPendingOrderRequestsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]OrderRequest, error) {
	rows, err := q.db.Query(ctx, listPendingOrderRequestsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderRequest{}
	for rows.Next() {
		var i OrderRequest
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CustomerContact,
			&i.RequestedItems,
			&i.Status,
			&i.DeclineReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.DeclineReasonCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderRequestStatus = `-- name: SetOrderRequestStatus :one
UPDATE order_requests
SET status = $2, decline_reason = $3, decline_reason_category = $4
WHERE id = $1
RETURNING id, merchant_id, customer_contact, requested_items, status, decline_reason, created_at, updated_at, customer_name, decline_reason_category
`

type SetOrderRequestStatusParams struct {
	ID                    pgtype.UUID `json:"id"`
	Status                string      `json:"status"`
	DeclineReason         pgtype.Text `json:"decline_reason"`
	DeclineReasonCategory pgtype.Text `json:"decline_reason_category"`
}

func (q *Queries) SetOrderRequestStatus(ctx context.Context, arg SetOrderRequestStatusParams) (OrderRequest, error) {
	row := q.db.QueryRow(ctx, setOrderRequestStatus,
		arg.ID,
		arg.Status,
		arg.DeclineReason,
		arg.DeclineReasonCategory,
	)
	var i OrderRequest
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerContact,
		&i.RequestedItems,
		&i.Status,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.DeclineReasonCategory,
	)
	return i, err
}
