// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: otp.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentPhoneOTPs = `-- name: CountRecentPhoneOTPs :one
SELECT COUNT(*) FROM phone_otps WHERE phone = $1 AND created_at > $2
`

type CountRecentPhoneOTPsParams struct {
	Phone     string             `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Rate-limit for RequestPhoneOTP: how many codes have been requested for
// this phone since [since] (e.g. the last hour).
func (q *Queries) CountRecentPhoneOTPs(ctx context.Context, arg CountRecentPhoneOTPsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentPhoneOTPs, arg.Phone, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhoneOTP = `-- name: CreatePhoneOTP :one
INSERT INTO phone_otps (phone, code, expires_at)
VALUES ($1, $2, $3)
RETURNING id, phone, code, attempt_count, verified_at, expires_at, created_at
`

type CreatePhoneOTPParams struct {
	Phone     string             `json:"phone"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePhoneOTP(ctx context.Context, arg CreatePhoneOTPParams) (PhoneOtp, error) {
	row := q.db.QueryRow(ctx, createPhoneOTP, arg.Phone, arg.Code, arg.ExpiresAt)
	var i PhoneOtp
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Code,
		&i.AttemptCount,
		&i.VerifiedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPhoneOTP = `-- name: GetLatestPhoneOTP :one
SELECT id, phone, code, attempt_count, verified_at, expires_at, created_at FROM phone_otps WHERE phone = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestPhoneOTP(ctx context.Context, phone string) (PhoneOtp, error) {
	row := q.db.QueryRow(ctx, getLatestPhoneOTP, phone)
	var i PhoneOtp
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Code,
		&i.AttemptCount,
		&i.VerifiedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentVerifiedPhoneOTP = `-- name: GetRecentVerifiedPhoneOTP :one
SELECT id, phone, code, attempt_count, verified_at, expires_at, created_at FROM phone_otps
WHERE phone = $1 AND verified_at IS NOT NULL AND verified_at > $2
ORDER BY verified_at DESC LIMIT 1
`

type GetRecentVerifiedPhoneOTPParams struct {
	Phone      string             `json:"phone"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
}

// CreateMerchant checks this to confirm the phone was actually OTP-verified
// (within [since], e.g. the last 30 minutes) before letting registration
// through Page 2 proceed.
func (q *Queries) GetRecentVerifiedPhoneOTP(ctx context.Context, arg GetRecentVerifiedPhoneOTPParams) (PhoneOtp, error) {
	row := q.db.QueryRow(ctx, getRecentVerifiedPhoneOTP, arg.Phone, arg.VerifiedAt)
	var i PhoneOtp
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Code,
		&i.AttemptCount,
		&i.VerifiedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPhoneOTPAttempts = `-- name: IncrementPhoneOTPAttempts :exec
UPDATE phone_otps SET attempt_count = attempt_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPhoneOTPAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementPhoneOTPAttempts, id)
	return err
}

const markPhoneOTPVerified = `-- name: MarkPhoneOTPVerified :exec
UPDATE phone_otps SET verified_at = now() WHERE id = $1
`

func (q *Queries) MarkPhoneOTPVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPhoneOTPVerified, id)
	return err
}
