// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (invoice_id, psp_reference, method, amount_pesewas, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, invoice_id, psp_reference, method, amount_pesewas, status, paid_at, created_at, psp_fee_pesewas, settlement_id, refunded_amount_pesewas
`

type CreatePaymentParams struct {
	InvoiceID     pgtype.UUID `json:"invoice_id"`
	PspReference  string      `json:"psp_reference"`
	Method        string      `json:"method"`
	AmountPesewas int64       `json:"amount_pesewas"`
	Status        string      `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.InvoiceID,
		arg.PspReference,
		arg.Method,
		arg.AmountPesewas,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.PspReference,
		&i.Method,
		&i.AmountPesewas,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.PspFeePesewas,
		&i.SettlementID,
		&i.RefundedAmountPesewas,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, invoice_id, psp_reference, method, amount_pesewas, status, paid_at, created_at, psp_fee_pesewas, settlement_id, refunded_amount_pesewas FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.PspReference,
		&i.Method,
		&i.AmountPesewas,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.PspFeePesewas,
		&i.SettlementID,
		&i.RefundedAmountPesewas,
	)
	return i, err
}

const getPaymentByPSPReference = `-- name: GetPaymentByPSPReference :one
SELECT id, invoice_id, psp_reference, method, amount_pesewas, status, paid_at, created_at, psp_fee_pesewas, settlement_id, refunded_amount_pesewas FROM payments WHERE psp_reference = $1
`

func (q *Queries) GetPaymentByPSPReference(ctx context.Context, pspReference string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByPSPReference, pspReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.PspReference,
		&i.Method,
		&i.AmountPesewas,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.PspFeePesewas,
		&i.SettlementID,
		&i.RefundedAmountPesewas,
	)
	return i, err
}

const listPaymentsByInvoice = `-- name: ListPaymentsByInvoice :many
SELECT id, invoice_id, psp_reference, method, amount_pesewas, status, paid_at, created_at, psp_fee_pesewas, settlement_id, refunded_amount_pesewas FROM payments WHERE invoice_id = $1 ORDER BY created_at
`

func (q *Queries) ListPaymentsByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.PspReference,
			&i.Method,
			&i.AmountPesewas,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.PspFeePesewas,
			&i.SettlementID,
			&i.RefundedAmountPesewas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentStatus = `-- name: SetPaymentStatus :one
UPDATE payments
SET status = $2, psp_fee_pesewas = $3, method = $4, paid_at = CASE WHEN $2 = 'success' THEN now() ELSE paid_at END
WHERE id = $1
RETURNING id, invoice_id, psp_reference, method, amount_pesewas, status, paid_at, created_at, psp_fee_pesewas, settlement_id, refunded_amount_pesewas
`

type SetPaymentStatusParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	PspFeePesewas int64       `json:"psp_fee_pesewas"`
	Method        string      `json:"method"`
}

func (q *Queries) SetPaymentStatus(ctx context.Context, arg SetPaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, setPaymentStatus,
		arg.ID,
		arg.Status,
		arg.PspFeePesewas,
		arg.Method,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.PspReference,
		&i.Method,
		&i.AmountPesewas,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.PspFeePesewas,
		&i.SettlementID,
		&i.RefundedAmountPesewas,
	)
	return i, err
}

const sumSuccessfulPaymentsByInvoice = `-- name: SumSuccessfulPaymentsByInvoice :one
SELECT COALESCE(SUM(amount_pesewas), 0)::bigint AS total_paid_pesewas
FROM payments
WHERE invoice_id = $1 AND status = 'success'
`

func (q *Queries) SumSuccessfulPaymentsByInvoice(ctx context.Context, invoiceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumSuccessfulPaymentsByInvoice, invoiceID)
	var total_paid_pesewas int64
	err := row.Scan(&total_paid_pesewas)
	return total_paid_pesewas, err
}
