// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFeatureFlagMerchant(ctx context.Context, arg AddFeatureFlagMerchantParams) error
	AddPaymentRefund(ctx context.Context, arg AddPaymentRefundParams) (Payment, error)
	ApplySettlementClawback(ctx context.Context, arg ApplySettlementClawbackParams) error
	// Used when a submission is approved: the tier and the fork that earned it
	// land together, so a Tier 2 merchant always carries business_type
	// 'registered' and the two can never drift apart.
	ApproveMerchantKYC(ctx context.Context, arg ApproveMerchantKYCParams) (Merchant, error)
	ArchiveItem(ctx context.Context, arg ArchiveItemParams) (int64, error)
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	// Step 1 of "set this location as default" — unset whatever the current
	// default is first so the partial unique index (merchant_id) WHERE
	// is_default never sees two defaults at once, even transiently.
	ClearDefaultMerchantLocation(ctx context.Context, merchantID pgtype.UUID) error
	// Section 7.2 batch-run reconciliation: sums every not-yet-settled
	// successful payment for the merchant in [period_start, period_end), and
	// prorates each invoice's commission/merchant-entitlement by how much of
	// that invoice was actually collected in the period — so a partially paid
	// invoice settles correctly on whichever payment(s) landed in this window,
	// without ever needing to touch a payment already claimed by an earlier
	// settlement (p.settlement_id IS NULL).
	//
	// Every sum below uses (amount_pesewas - refunded_amount_pesewas), not the
	// raw amount — a payment refunded before it was ever settled must not still
	// pay the merchant, or book OrderxPay commission, on money that already
	// went back to the customer. A payment refunded *after* settlement is a
	// different problem entirely (the merchant was already paid) — see
	// settlement_clawbacks and GenerateSettlement for that half.
	ComputeSettlementAggregate(ctx context.Context, arg ComputeSettlementAggregateParams) (ComputeSettlementAggregateRow, error)
	// Rate-limit for RequestPhoneOTP: how many codes have been requested for
	// this phone since [since] (e.g. the last hour).
	CountRecentPhoneOTPs(ctx context.Context, arg CountRecentPhoneOTPsParams) (int64, error)
	CountUnreadNotifications(ctx context.Context, merchantID pgtype.UUID) (int64, error)
	CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (AuditLogEntry, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateDeliveryOption(ctx context.Context, arg CreateDeliveryOptionParams) (DeliveryOption, error)
	CreateDeliveryProvider(ctx context.Context, arg CreateDeliveryProviderParams) (DeliveryProvider, error)
	CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error)
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateInvoiceLineItem(ctx context.Context, arg CreateInvoiceLineItemParams) (InvoiceLineItem, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	// requested_tier is not caller-chosen: the schema pins informal to 1 and
	// registered to 2, so the tier always matches the evidence reviewed.
	CreateKYCSubmission(ctx context.Context, arg CreateKYCSubmissionParams) (KycSubmission, error)
	CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreateMerchantLocation(ctx context.Context, arg CreateMerchantLocationParams) (MerchantLocation, error)
	CreateMerchantNote(ctx context.Context, arg CreateMerchantNoteParams) (MerchantNote, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOrderRequest(ctx context.Context, arg CreateOrderRequestParams) (OrderRequest, error)
	// paystack_subaccount_code is set only when this specific charge was split
	// at initialize time — null (the default) is the ordinary path, unchanged
	// from before split payments existed. provider defaults to 'paystack' at
	// the schema level (Paystack was the only provider before Hubtel USSD
	// existed) but is passed explicitly here so a Hubtel-initiated payment can
	// say so.
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePhoneOTP(ctx context.Context, arg CreatePhoneOTPParams) (PhoneOtp, error)
	// Silently skipped when an identical open flag already exists
	// (risk_flags_dedupe_open) — a scan re-run should never spam duplicates.
	CreateRiskFlag(ctx context.Context, arg CreateRiskFlagParams) error
	CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error)
	// Section 7.7: records what a merchant now owes back because a payment
	// that already went through a completed settlement got refunded. See
	// 000034's migration comment for why amount_pesewas is the merchant's
	// entitled share of the refund, not the whole refund.
	CreateSettlementClawback(ctx context.Context, arg CreateSettlementClawbackParams) (SettlementClawback, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) error
	DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) (int64, error)
	DeleteDeliveryProvider(ctx context.Context, id pgtype.UUID) error
	DeleteDeviceToken(ctx context.Context, fcmToken string) error
	DeleteMenu(ctx context.Context, id pgtype.UUID) error
	DeleteMerchantFeeRule(ctx context.Context, merchantID pgtype.UUID) error
	// merchant_id in the WHERE clause, not just id — a staff row belongs to
	// exactly one merchant, and the caller must own it (RowsAffected() == 0
	// means either it doesn't exist or belongs to someone else; either way
	// the handler reports 404, not which).
	DeleteStaff(ctx context.Context, arg DeleteStaffParams) (int64, error)
	// One row per merchant that shares a Ghana Card number with at least one
	// other merchant's KYC submission (any status — even a rejected submission
	// reusing someone else's card number is a real signal).
	FindDuplicateGhanaCardFlags(ctx context.Context) ([]FindDuplicateGhanaCardFlagsRow, error)
	// Flags a merchant whose trailing-24h invoice count or value is both above
	// a floor (so a brand-new merchant's first few invoices don't trip it) and
	// a multiple of their own trailing 7-day daily average (so an
	// already-high-volume merchant isn't flagged just for staying busy).
	FindVelocitySpikes(ctx context.Context) ([]FindVelocitySpikesRow, error)
	GetCustomer(ctx context.Context, id pgtype.UUID) (Customer, error)
	// Daily time series for the same period — only days with at least one
	// successful payment (a table doesn't need zero-filled gap rows the way a
	// chart would).
	GetDailyRevenue(ctx context.Context, arg GetDailyRevenueParams) ([]GetDailyRevenueRow, error)
	GetDeliveryOption(ctx context.Context, id pgtype.UUID) (DeliveryOption, error)
	GetDispute(ctx context.Context, id pgtype.UUID) (Dispute, error)
	GetEmailVerificationByToken(ctx context.Context, token string) (EmailVerification, error)
	GetFeatureFlag(ctx context.Context, id pgtype.UUID) (FeatureFlag, error)
	// Enabled if flipped on for everyone, or this merchant is specifically
	// opted in during a staged rollout (Section 7.4). Returns false (not an
	// error) when the key doesn't exist, so callers checking a not-yet-seeded
	// flag key just see "off" rather than needing separate not-found handling.
	GetFeatureFlagStatusForMerchant(ctx context.Context, arg GetFeatureFlagStatusForMerchantParams) (bool, error)
	GetFeeRuleByMerchant(ctx context.Context, merchantID pgtype.UUID) (FeeRule, error)
	GetGlobalFeeRule(ctx context.Context) (FeeRule, error)
	GetIntegration(ctx context.Context, providerKey string) (Integration, error)
	GetInvoice(ctx context.Context, id pgtype.UUID) (Invoice, error)
	GetInvoiceByReference(ctx context.Context, reference string) (Invoice, error)
	// Single-param, unscoped by merchant — used internally by the invoice
	// engine (resolveLineItems), which does its own explicit ownership compare
	// against the item it fetches. Route handlers should use
	// GetItemOwnedByMerchant instead.
	GetItem(ctx context.Context, id pgtype.UUID) (Item, error)
	GetItemOwnedByMerchant(ctx context.Context, arg GetItemOwnedByMerchantParams) (Item, error)
	GetKYCSubmission(ctx context.Context, id pgtype.UUID) (KycSubmission, error)
	GetKYCTierLimit(ctx context.Context, tier int16) (KycTierLimit, error)
	GetLatestPhoneOTP(ctx context.Context, phone string) (PhoneOtp, error)
	GetMenu(ctx context.Context, id pgtype.UUID) (Menu, error)
	GetMerchant(ctx context.Context, id pgtype.UUID) (Merchant, error)
	// Section 4.7: merchant-facing analytics + bookkeeping export. All queries
	// are merchant-scoped (mounted under RequireOwnMerchant) and, unless noted,
	// only count invoices that actually collected money (paid or
	// partially_paid) within the requested period — a declined/expired invoice
	// isn't a "sale".
	GetMerchantBestSellingItems(ctx context.Context, arg GetMerchantBestSellingItemsParams) ([]GetMerchantBestSellingItemsRow, error)
	GetMerchantByEmail(ctx context.Context, dollar_1 string) (Merchant, error)
	GetMerchantByPhone(ctx context.Context, phone string) (Merchant, error)
	// Attributes an inbound WhatsApp webhook to a merchant — see
	// internal/whatsapp and handlers/whatsapp.go.
	GetMerchantByWhatsAppPhoneNumberID(ctx context.Context, dollar_1 string) (Merchant, error)
	// Grouped by actual payment date (not invoice date), matching the platform-
	// wide GetDailyRevenue query in reporting.sql.
	GetMerchantDailyCollections(ctx context.Context, arg GetMerchantDailyCollectionsParams) ([]GetMerchantDailyCollectionsRow, error)
	GetMerchantLocation(ctx context.Context, id pgtype.UUID) (MerchantLocation, error)
	GetMerchantOrderStats(ctx context.Context, arg GetMerchantOrderStatsParams) (GetMerchantOrderStatsRow, error)
	// A "repeat" customer placed more than one paid/partially-paid order in the
	// period, identified by customer_contact since there's no customers table.
	GetMerchantRepeatCustomers(ctx context.Context, arg GetMerchantRepeatCustomersParams) ([]GetMerchantRepeatCustomersRow, error)
	// Section 7.5: one row per merchant for the selected period — LEFT JOINs
	// so a merchant with zero activity in the period still appears (with all
	// figures at 0), which is exactly what "active vs. dormant" needs to be
	// computed from in Go rather than a second query. Commission is prorated
	// by how much of each invoice was actually collected in the period, the
	// same pattern as the settlement engine's ComputeSettlementAggregate.
	GetMerchantRevenueBreakdown(ctx context.Context, arg GetMerchantRevenueBreakdownParams) ([]GetMerchantRevenueBreakdownRow, error)
	// Collected volume for limit checks, measured on successful payments rather
	// than invoice totals: an invoice that was raised but never paid moved no
	// money and must not consume a merchant's headroom.
	//
	// Deliberately gross, not net of refunds — otherwise a merchant could
	// refund their way back under a cap and transact the same money twice. The
	// daily window is a plain UTC calendar day, which is Ghana local time
	// year-round (UTC+0, no DST).
	GetMerchantVolume(ctx context.Context, merchantID pgtype.UUID) (GetMerchantVolumeRow, error)
	GetOpenKYCSubmissionByMerchant(ctx context.Context, merchantID pgtype.UUID) (KycSubmission, error)
	GetOrderRequest(ctx context.Context, id pgtype.UUID) (OrderRequest, error)
	GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error)
	GetPaymentByPSPReference(ctx context.Context, pspReference string) (Payment, error)
	GetPermissionByKey(ctx context.Context, key string) (Permission, error)
	// CreateMerchant checks this to confirm the phone was actually OTP-verified
	// (within [since], e.g. the last 30 minutes) before letting registration
	// through Page 2 proceed.
	GetRecentVerifiedPhoneOTP(ctx context.Context, arg GetRecentVerifiedPhoneOTPParams) (PhoneOtp, error)
	GetRiskFlag(ctx context.Context, id pgtype.UUID) (RiskFlag, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetSettlement(ctx context.Context, id pgtype.UUID) (Settlement, error)
	GetStaffByEmail(ctx context.Context, dollar_1 string) (Staff, error)
	GetStaffByPhone(ctx context.Context, phone string) (Staff, error)
	GetSupportTransaction(ctx context.Context, reference string) (GetSupportTransactionRow, error)
	// The row-level side of margin reconciliation: individual successful
	// payments in the period where the PSP fee Paystack actually reported came
	// out higher than the commission booked against that payment. Commission is
	// prorated across partial payments the same way GetMerchantRevenueBreakdown
	// does it. An aggregate can't show this — a single delivery-heavy invoice
	// that lost money disappears the moment it is summed into a merchant who is
	// net positive, which is exactly how the bundled-delivery leak stayed
	// invisible. Capped at 100; ordered worst-first.
	GetUnderwaterPayments(ctx context.Context, arg GetUnderwaterPaymentsParams) ([]GetUnderwaterPaymentsRow, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// GetUserPermissionKeys is the union of permissions granted via the user's
	// roles and any direct per-user grants — this is what gets embedded in the
	// PASETO token payload at login time.
	GetUserPermissionKeys(ctx context.Context, userID pgtype.UUID) ([]string, error)
	GrantUserPermission(ctx context.Context, arg GrantUserPermissionParams) error
	// Section 4.2: item photo uploads. delta is the file size in bytes — always
	// positive today (nothing decrements it yet; replacing/archiving an item's
	// photo leaves the old file's bytes counted, a known simplification for
	// this first pass).
	IncrementMerchantStorageUsed(ctx context.Context, arg IncrementMerchantStorageUsedParams) (Merchant, error)
	IncrementPhoneOTPAttempts(ctx context.Context, id pgtype.UUID) error
	// Merchant-app side of the admin-maintained catalog (Section 4.11/9.4) —
	// only what's actually active, unlike the admin list above which needs to
	// see inactive/retired entries too for management.
	ListActiveDeliveryProviders(ctx context.Context) ([]DeliveryProvider, error)
	// Section 7.9 compliance log view. Joins to users for a display name/email
	// when actor_type = 'user' — 'system'-actor entries (webhook/reconciliation
	// writes) have no row to join and are left as actor_name = NULL.
	ListAuditLogEntriesAdmin(ctx context.Context, arg ListAuditLogEntriesAdminParams) ([]ListAuditLogEntriesAdminRow, error)
	ListAuditLogEntriesByTarget(ctx context.Context, arg ListAuditLogEntriesByTargetParams) ([]AuditLogEntry, error)
	// Distinct target_entity values seen so far, to populate the filter dropdown.
	ListAuditLogTargetEntities(ctx context.Context) ([]string, error)
	ListConversationsByMerchant(ctx context.Context, arg ListConversationsByMerchantParams) ([]Conversation, error)
	ListCustomers(ctx context.Context, merchantID pgtype.UUID) ([]Customer, error)
	ListDeliveryOptionsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]DeliveryOption, error)
	ListDeliveryProviders(ctx context.Context) ([]DeliveryProvider, error)
	ListDeviceTokensByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]DeviceToken, error)
	ListDisputesAdmin(ctx context.Context, arg ListDisputesAdminParams) ([]ListDisputesAdminRow, error)
	ListFeatureFlagMerchants(ctx context.Context, featureFlagID pgtype.UUID) ([]ListFeatureFlagMerchantsRow, error)
	ListFeatureFlags(ctx context.Context) ([]FeatureFlag, error)
	ListIntegrations(ctx context.Context) ([]Integration, error)
	ListInvoiceLineItems(ctx context.Context, invoiceID pgtype.UUID) ([]InvoiceLineItem, error)
	ListInvoicesByMerchant(ctx context.Context, arg ListInvoicesByMerchantParams) ([]Invoice, error)
	ListItemsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Item, error)
	ListKYCSubmissionsAdmin(ctx context.Context, arg ListKYCSubmissionsAdminParams) ([]ListKYCSubmissionsAdminRow, error)
	ListKYCSubmissionsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]KycSubmission, error)
	ListKYCTierLimits(ctx context.Context) ([]KycTierLimit, error)
	ListMenus(ctx context.Context) ([]Menu, error)
	// ListMenusForUser returns every menu with no permission requirement, every
	// menu whose permission is among the caller's effective permissions (via
	// role or direct grant), AND every ancestor of such a menu — otherwise a
	// child could pass its own permission check while its parent doesn't,
	// leaving it with no reachable parent in the assembled tree. This is what
	// the Back Office sidebar calls.
	ListMenusForUser(ctx context.Context, userID pgtype.UUID) ([]ListMenusForUserRow, error)
	ListMerchantFeeRuleOverrides(ctx context.Context) ([]ListMerchantFeeRuleOverridesRow, error)
	// Backs the CSV bookkeeping export — every invoice in the period regardless
	// of status (an accountant needs to see declined/expired ones too), with
	// items and the payment method(s) used summarized per row.
	ListMerchantInvoicesForExport(ctx context.Context, arg ListMerchantInvoicesForExportParams) ([]ListMerchantInvoicesForExportRow, error)
	ListMerchantLocationsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]MerchantLocation, error)
	ListMerchantNotes(ctx context.Context, merchantID pgtype.UUID) ([]ListMerchantNotesRow, error)
	ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error)
	ListNotificationsByMerchant(ctx context.Context, arg ListNotificationsByMerchantParams) ([]Notification, error)
	// Oldest first — GenerateSettlement consumes a merchant's debt in this
	// order, one whole clawback at a time (see that function's comment on why
	// a clawback is never split across settlements).
	ListOutstandingClawbacksByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]SettlementClawback, error)
	ListPaymentsByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]Payment, error)
	ListPendingOrderRequestsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]OrderRequest, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListPermissionsByRole(ctx context.Context, roleID pgtype.UUID) ([]Permission, error)
	ListRiskFlagsAdmin(ctx context.Context, arg ListRiskFlagsAdminParams) ([]ListRiskFlagsAdminRow, error)
	// Backs the Section 7.1 merchant detail view's "flags" panel.
	ListRiskFlagsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]RiskFlag, error)
	ListRoles(ctx context.Context) ([]Role, error)
	// Cross-merchant view backing the Back Office 7.2 landing page — the
	// per-merchant ListSettlementsByMerchant above stays as-is for the merchant
	// detail page's drill-down.
	ListSettlementsAdmin(ctx context.Context, arg ListSettlementsAdminParams) ([]ListSettlementsAdminRow, error)
	ListSettlementsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Settlement, error)
	ListStaffByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Staff, error)
	ListUserDirectPermissions(ctx context.Context, userID pgtype.UUID) ([]Permission, error)
	ListUserRoles(ctx context.Context, userID pgtype.UUID) ([]Role, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error)
	MarkAllNotificationsRead(ctx context.Context, merchantID pgtype.UUID) error
	MarkEmailVerificationUsed(ctx context.Context, id pgtype.UUID) error
	MarkMerchantEmailVerified(ctx context.Context, id pgtype.UUID) (Merchant, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	// Stamps every payment just aggregated into ComputeSettlementAggregate with
	// the resulting settlement's id — must run with the exact same filter, in
	// the same transaction, or a payment could be double-counted by a later run.
	MarkPaymentsSettled(ctx context.Context, arg MarkPaymentsSettledParams) error
	MarkPhoneOTPVerified(ctx context.Context, id pgtype.UUID) error
	RemoveFeatureFlagMerchant(ctx context.Context, arg RemoveFeatureFlagMerchantParams) error
	RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error
	ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (Dispute, error)
	ResolveRiskFlag(ctx context.Context, arg ResolveRiskFlagParams) (RiskFlag, error)
	// Reuses the existing row after a more_info_requested response instead of
	// inserting a second one — kyc_submissions_one_open_per_merchant would
	// reject a second open row anyway, and this is the correct UX: the
	// reviewer's original notes/decision get replaced by the fresh review cycle.
	// A resubmission may also switch fork — an informal trader who registers
	// their business between review cycles resubmits as 'registered', and
	// requested_tier moves with it.
	ResubmitKYCSubmission(ctx context.Context, arg ResubmitKYCSubmissionParams) (KycSubmission, error)
	ReviewKYCSubmission(ctx context.Context, arg ReviewKYCSubmissionParams) (KycSubmission, error)
	RevokeUserPermission(ctx context.Context, arg RevokeUserPermissionParams) error
	// Matches on invoice reference or customer phone — the two things a support
	// agent is handed on a call ("my order is ORD-1234" / "I paid with 024...").
	SearchInvoicesForSupport(ctx context.Context, query string) ([]SearchInvoicesForSupportRow, error)
	SearchMerchantsForSupport(ctx context.Context, query string) ([]Merchant, error)
	SetDefaultMerchantLocation(ctx context.Context, arg SetDefaultMerchantLocationParams) (int64, error)
	// merchant_id in the WHERE clause — the route path only carries the
	// delivery option's own id, not a merchant id, so ownership has to be
	// enforced here against the caller's token instead.
	SetDeliveryOptionStatus(ctx context.Context, arg SetDeliveryOptionStatusParams) (int64, error)
	// Non-terminal transition only (e.g. open -> investigating) — no
	// resolution fields; see ResolveDispute for the terminal transitions.
	SetDisputeStatus(ctx context.Context, arg SetDisputeStatusParams) (Dispute, error)
	SetFeatureFlagGlobal(ctx context.Context, arg SetFeatureFlagGlobalParams) (FeatureFlag, error)
	SetIntegrationSecret(ctx context.Context, arg SetIntegrationSecretParams) (Integration, error)
	SetInvoiceStatus(ctx context.Context, arg SetInvoiceStatusParams) (Invoice, error)
	SetOrderRequestStatus(ctx context.Context, arg SetOrderRequestStatusParams) (OrderRequest, error)
	SetPaymentStatus(ctx context.Context, arg SetPaymentStatusParams) (Payment, error)
	SetSettlementStatus(ctx context.Context, arg SetSettlementStatusParams) (Settlement, error)
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error)
	SumSuccessfulPaymentsByInvoice(ctx context.Context, invoiceID pgtype.UUID) (int64, error)
	// Ownership enforced in the WHERE clause, same pattern as
	// UpdateMerchantLocation — the route path only carries the customer's
	// own id, not the merchant id.
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (int64, error)
	// Full edit — contact/provider details, flat fee/zone, and fee handling —
	// used by the Delivery Settings screen's edit sheet and by the inline
	// fee-handling selector on already-enabled catalog providers. Same
	// ownership-in-WHERE pattern as SetDeliveryOptionStatus above.
	UpdateDeliveryOption(ctx context.Context, arg UpdateDeliveryOptionParams) (int64, error)
	UpdateDeliveryProvider(ctx context.Context, arg UpdateDeliveryProviderParams) (DeliveryProvider, error)
	UpdateIntegrationNotes(ctx context.Context, arg UpdateIntegrationNotesParams) (Integration, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
	// NULL on any column means "no cap" — the enforcement path skips an unset
	// limit rather than treating it as zero.
	UpdateKYCTierLimit(ctx context.Context, arg UpdateKYCTierLimitParams) (KycTierLimit, error)
	UpdateMenu(ctx context.Context, arg UpdateMenuParams) (Menu, error)
	UpdateMerchantDeliveryEnabled(ctx context.Context, arg UpdateMerchantDeliveryEnabledParams) (Merchant, error)
	UpdateMerchantEmail(ctx context.Context, arg UpdateMerchantEmailParams) (Merchant, error)
	UpdateMerchantFeeSettings(ctx context.Context, arg UpdateMerchantFeeSettingsParams) (Merchant, error)
	// Used by the Back Office tier override, which moves the tier without a
	// submission behind it and so leaves business_type alone.
	UpdateMerchantKYCTier(ctx context.Context, arg UpdateMerchantKYCTierParams) (Merchant, error)
	// Ownership enforced in the WHERE clause, same pattern as
	// UpdateDeliveryOption — the route path only carries the location's own
	// id, not the merchant id.
	UpdateMerchantLocation(ctx context.Context, arg UpdateMerchantLocationParams) (int64, error)
	UpdateMerchantPassword(ctx context.Context, arg UpdateMerchantPasswordParams) (Merchant, error)
	// account_name and verified_at travel together with the account details
	// they describe — never set independently, so a resolved name can never
	// outlive the account number it was resolved against. See
	// UpdateMerchantPayoutAccountParams' caller (SetPayoutAccount) for the
	// rule that clears them back to null whenever the account itself changes.
	UpdateMerchantPayoutAccount(ctx context.Context, arg UpdateMerchantPayoutAccountParams) (Merchant, error)
	UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (Merchant, error)
	// Provisioning-only: records the Paystack subaccount created/updated
	// alongside a verified payout account (SetPayoutAccount in
	// payout_account.go). Never changes how any payment routes by itself —
	// see InitiateCheckoutPayment for the only place that reads this and
	// actually splits a charge.
	UpdateMerchantSubaccountCode(ctx context.Context, arg UpdateMerchantSubaccountCodeParams) (Merchant, error)
	// Admin-only provisioning step (Section 6.2), same reasoning as
	// UpdateMerchantWhatsAppPhoneNumberID: an admin creates the catalog in
	// Meta Commerce Manager and connects it to the merchant's WhatsApp
	// Business Account, then records the resulting catalog_id here — no
	// merchant self-service path exists for this.
	UpdateMerchantWhatsAppCatalogID(ctx context.Context, arg UpdateMerchantWhatsAppCatalogIDParams) (Merchant, error)
	// Admin-only provisioning step (Section 7.3): OrderxPay registers the
	// merchant's number under the platform WABA in Meta's console, then
	// records the resulting phone_number_id here.
	UpdateMerchantWhatsAppPhoneNumberID(ctx context.Context, arg UpdateMerchantWhatsAppPhoneNumberIDParams) (Merchant, error)
	UpdateMerchantWhatsAppSettings(ctx context.Context, arg UpdateMerchantWhatsAppSettingsParams) (Merchant, error)
	UpdateStaffPassword(ctx context.Context, arg UpdateStaffPasswordParams) (Staff, error)
	// Best-effort auto-save (called after every invoice send) and the
	// manual "+ Add Customer" path share this same query — both are really
	// "remember this contact, keeping whatever name we already know unless
	// a better one just showed up." COALESCE keeps an existing name intact
	// when this particular call doesn't have one (EXCLUDED.name NULL).
	UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (Customer, error)
	// Re-registering the same token (app relaunch) just bumps updated_at; a
	// token that moved to a different merchant (see migration comment) is
	// repointed rather than rejected.
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error)
	// commission_bps is derived server-side (collection + margin) so it can never
	// drift from what the components actually add up to — every other reader
	// (invoice engine, checkout) still just reads the one blended number.
	UpsertGlobalFeeRule(ctx context.Context, arg UpsertGlobalFeeRuleParams) (FeeRule, error)
	UpsertMerchantFeeRule(ctx context.Context, arg UpsertMerchantFeeRuleParams) (FeeRule, error)
}

var _ Querier = (*Queries)(nil)
