// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFeatureFlagMerchant(ctx context.Context, arg AddFeatureFlagMerchantParams) error
	AddPaymentRefund(ctx context.Context, arg AddPaymentRefundParams) (Payment, error)
	ArchiveItem(ctx context.Context, id pgtype.UUID) error
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	// Section 7.2 batch-run reconciliation: sums every not-yet-settled
	// successful payment for the merchant in [period_start, period_end), and
	// prorates each invoice's commission/merchant-entitlement by how much of
	// that invoice was actually collected in the period — so a partially paid
	// invoice settles correctly on whichever payment(s) landed in this window,
	// without ever needing to touch a payment already claimed by an earlier
	// settlement (p.settlement_id IS NULL).
	ComputeSettlementAggregate(ctx context.Context, arg ComputeSettlementAggregateParams) (ComputeSettlementAggregateRow, error)
	CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (AuditLogEntry, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateDeliveryOption(ctx context.Context, arg CreateDeliveryOptionParams) (DeliveryOption, error)
	CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateInvoiceLineItem(ctx context.Context, arg CreateInvoiceLineItemParams) (InvoiceLineItem, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateKYCSubmission(ctx context.Context, arg CreateKYCSubmissionParams) (KycSubmission, error)
	CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreateOrderRequest(ctx context.Context, arg CreateOrderRequestParams) (OrderRequest, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	// Silently skipped when an identical open flag already exists
	// (risk_flags_dedupe_open) — a scan re-run should never spam duplicates.
	CreateRiskFlag(ctx context.Context, arg CreateRiskFlagParams) error
	CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMenu(ctx context.Context, id pgtype.UUID) error
	DeleteMerchantFeeRule(ctx context.Context, merchantID pgtype.UUID) error
	DeleteStaff(ctx context.Context, id pgtype.UUID) error
	// One row per merchant that shares a Ghana Card number with at least one
	// other merchant's KYC submission (any status — even a rejected submission
	// reusing someone else's card number is a real signal).
	FindDuplicateGhanaCardFlags(ctx context.Context) ([]FindDuplicateGhanaCardFlagsRow, error)
	// Flags a merchant whose trailing-24h invoice count or value is both above
	// a floor (so a brand-new merchant's first few invoices don't trip it) and
	// a multiple of their own trailing 7-day daily average (so an
	// already-high-volume merchant isn't flagged just for staying busy).
	FindVelocitySpikes(ctx context.Context) ([]FindVelocitySpikesRow, error)
	// Daily time series for the same period — only days with at least one
	// successful payment (a table doesn't need zero-filled gap rows the way a
	// chart would).
	GetDailyRevenue(ctx context.Context, arg GetDailyRevenueParams) ([]GetDailyRevenueRow, error)
	GetDeliveryOption(ctx context.Context, id pgtype.UUID) (DeliveryOption, error)
	GetDispute(ctx context.Context, id pgtype.UUID) (Dispute, error)
	GetFeatureFlag(ctx context.Context, id pgtype.UUID) (FeatureFlag, error)
	GetFeeRuleByMerchant(ctx context.Context, merchantID pgtype.UUID) (FeeRule, error)
	GetGlobalFeeRule(ctx context.Context) (FeeRule, error)
	GetInvoice(ctx context.Context, id pgtype.UUID) (Invoice, error)
	GetInvoiceByReference(ctx context.Context, reference string) (Invoice, error)
	GetItem(ctx context.Context, id pgtype.UUID) (Item, error)
	GetKYCSubmission(ctx context.Context, id pgtype.UUID) (KycSubmission, error)
	GetMenu(ctx context.Context, id pgtype.UUID) (Menu, error)
	GetMerchant(ctx context.Context, id pgtype.UUID) (Merchant, error)
	GetMerchantByPhone(ctx context.Context, phone string) (Merchant, error)
	// Section 7.5: one row per merchant for the selected period — LEFT JOINs
	// so a merchant with zero activity in the period still appears (with all
	// figures at 0), which is exactly what "active vs. dormant" needs to be
	// computed from in Go rather than a second query. Commission is prorated
	// by how much of each invoice was actually collected in the period, the
	// same pattern as the settlement engine's ComputeSettlementAggregate.
	GetMerchantRevenueBreakdown(ctx context.Context, arg GetMerchantRevenueBreakdownParams) ([]GetMerchantRevenueBreakdownRow, error)
	GetOpenKYCSubmissionByMerchant(ctx context.Context, merchantID pgtype.UUID) (KycSubmission, error)
	GetOrderRequest(ctx context.Context, id pgtype.UUID) (OrderRequest, error)
	GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error)
	GetPaymentByPSPReference(ctx context.Context, pspReference string) (Payment, error)
	GetPermissionByKey(ctx context.Context, key string) (Permission, error)
	GetRiskFlag(ctx context.Context, id pgtype.UUID) (RiskFlag, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetSettlement(ctx context.Context, id pgtype.UUID) (Settlement, error)
	GetStaffByPhone(ctx context.Context, phone string) (Staff, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// GetUserPermissionKeys is the union of permissions granted via the user's
	// roles and any direct per-user grants — this is what gets embedded in the
	// PASETO token payload at login time.
	GetUserPermissionKeys(ctx context.Context, userID pgtype.UUID) ([]string, error)
	GrantUserPermission(ctx context.Context, arg GrantUserPermissionParams) error
	ListAuditLogEntriesByTarget(ctx context.Context, arg ListAuditLogEntriesByTargetParams) ([]AuditLogEntry, error)
	ListConversationsByMerchant(ctx context.Context, arg ListConversationsByMerchantParams) ([]Conversation, error)
	ListDeliveryOptionsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]DeliveryOption, error)
	ListDisputesAdmin(ctx context.Context, arg ListDisputesAdminParams) ([]ListDisputesAdminRow, error)
	ListFeatureFlagMerchants(ctx context.Context, featureFlagID pgtype.UUID) ([]ListFeatureFlagMerchantsRow, error)
	ListFeatureFlags(ctx context.Context) ([]FeatureFlag, error)
	ListInvoiceLineItems(ctx context.Context, invoiceID pgtype.UUID) ([]InvoiceLineItem, error)
	ListInvoicesByMerchant(ctx context.Context, arg ListInvoicesByMerchantParams) ([]Invoice, error)
	ListItemsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Item, error)
	ListKYCSubmissionsAdmin(ctx context.Context, arg ListKYCSubmissionsAdminParams) ([]ListKYCSubmissionsAdminRow, error)
	ListKYCSubmissionsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]KycSubmission, error)
	ListMenus(ctx context.Context) ([]Menu, error)
	// ListMenusForUser returns every menu with no permission requirement, every
	// menu whose permission is among the caller's effective permissions (via
	// role or direct grant), AND every ancestor of such a menu — otherwise a
	// child could pass its own permission check while its parent doesn't,
	// leaving it with no reachable parent in the assembled tree. This is what
	// the Back Office sidebar calls.
	ListMenusForUser(ctx context.Context, userID pgtype.UUID) ([]ListMenusForUserRow, error)
	ListMerchantFeeRuleOverrides(ctx context.Context) ([]ListMerchantFeeRuleOverridesRow, error)
	ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error)
	ListPaymentsByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]Payment, error)
	ListPendingOrderRequestsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]OrderRequest, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListPermissionsByRole(ctx context.Context, roleID pgtype.UUID) ([]Permission, error)
	ListRiskFlagsAdmin(ctx context.Context, arg ListRiskFlagsAdminParams) ([]ListRiskFlagsAdminRow, error)
	ListRoles(ctx context.Context) ([]Role, error)
	// Cross-merchant view backing the Back Office 7.2 landing page — the
	// per-merchant ListSettlementsByMerchant above stays as-is for the merchant
	// detail page's drill-down.
	ListSettlementsAdmin(ctx context.Context, arg ListSettlementsAdminParams) ([]ListSettlementsAdminRow, error)
	ListSettlementsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Settlement, error)
	ListStaffByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Staff, error)
	ListUserDirectPermissions(ctx context.Context, userID pgtype.UUID) ([]Permission, error)
	ListUserRoles(ctx context.Context, userID pgtype.UUID) ([]Role, error)
	ListUsers(ctx context.Context) ([]User, error)
	// Stamps every payment just aggregated into ComputeSettlementAggregate with
	// the resulting settlement's id — must run with the exact same filter, in
	// the same transaction, or a payment could be double-counted by a later run.
	MarkPaymentsSettled(ctx context.Context, arg MarkPaymentsSettledParams) error
	RemoveFeatureFlagMerchant(ctx context.Context, arg RemoveFeatureFlagMerchantParams) error
	RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error
	ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (Dispute, error)
	ResolveRiskFlag(ctx context.Context, arg ResolveRiskFlagParams) (RiskFlag, error)
	// Reuses the existing row after a more_info_requested response instead of
	// inserting a second one — kyc_submissions_one_open_per_merchant would
	// reject a second open row anyway, and this is the correct UX: the
	// reviewer's original notes/decision get replaced by the fresh review cycle.
	ResubmitKYCSubmission(ctx context.Context, arg ResubmitKYCSubmissionParams) (KycSubmission, error)
	ReviewKYCSubmission(ctx context.Context, arg ReviewKYCSubmissionParams) (KycSubmission, error)
	RevokeUserPermission(ctx context.Context, arg RevokeUserPermissionParams) error
	SetDeliveryOptionStatus(ctx context.Context, arg SetDeliveryOptionStatusParams) error
	// Non-terminal transition only (e.g. open -> investigating) — no
	// resolution fields; see ResolveDispute for the terminal transitions.
	SetDisputeStatus(ctx context.Context, arg SetDisputeStatusParams) (Dispute, error)
	SetFeatureFlagGlobal(ctx context.Context, arg SetFeatureFlagGlobalParams) (FeatureFlag, error)
	SetInvoiceStatus(ctx context.Context, arg SetInvoiceStatusParams) (Invoice, error)
	SetOrderRequestStatus(ctx context.Context, arg SetOrderRequestStatusParams) (OrderRequest, error)
	SetPaymentStatus(ctx context.Context, arg SetPaymentStatusParams) (Payment, error)
	SetSettlementStatus(ctx context.Context, arg SetSettlementStatusParams) (Settlement, error)
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error)
	SumSuccessfulPaymentsByInvoice(ctx context.Context, invoiceID pgtype.UUID) (int64, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
	UpdateMenu(ctx context.Context, arg UpdateMenuParams) (Menu, error)
	UpdateMerchantFeeSettings(ctx context.Context, arg UpdateMerchantFeeSettingsParams) (Merchant, error)
	UpdateMerchantKYCTier(ctx context.Context, arg UpdateMerchantKYCTierParams) (Merchant, error)
	UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (Merchant, error)
	UpsertGlobalFeeRule(ctx context.Context, arg UpsertGlobalFeeRuleParams) (FeeRule, error)
	UpsertMerchantFeeRule(ctx context.Context, arg UpsertMerchantFeeRuleParams) (FeeRule, error)
}

var _ Querier = (*Queries)(nil)
