// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveItem(ctx context.Context, id pgtype.UUID) error
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error)
	CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (AuditLogEntry, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateDeliveryOption(ctx context.Context, arg CreateDeliveryOptionParams) (DeliveryOption, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateInvoiceLineItem(ctx context.Context, arg CreateInvoiceLineItemParams) (InvoiceLineItem, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreateOrderRequest(ctx context.Context, arg CreateOrderRequestParams) (OrderRequest, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error)
	DeleteStaff(ctx context.Context, id pgtype.UUID) error
	GetAdminUser(ctx context.Context, id pgtype.UUID) (AdminUser, error)
	GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error)
	GetDeliveryOption(ctx context.Context, id pgtype.UUID) (DeliveryOption, error)
	GetFeeRuleByMerchant(ctx context.Context, merchantID pgtype.UUID) (FeeRule, error)
	GetGlobalFeeRule(ctx context.Context) (FeeRule, error)
	GetInvoice(ctx context.Context, id pgtype.UUID) (Invoice, error)
	GetInvoiceByReference(ctx context.Context, reference string) (Invoice, error)
	GetItem(ctx context.Context, id pgtype.UUID) (Item, error)
	GetMerchant(ctx context.Context, id pgtype.UUID) (Merchant, error)
	GetMerchantByPhone(ctx context.Context, phone string) (Merchant, error)
	GetOrderRequest(ctx context.Context, id pgtype.UUID) (OrderRequest, error)
	GetPaymentByPSPReference(ctx context.Context, pspReference string) (Payment, error)
	GetStaffByPhone(ctx context.Context, phone string) (Staff, error)
	ListAdminUsers(ctx context.Context) ([]AdminUser, error)
	ListAuditLogEntriesByTarget(ctx context.Context, arg ListAuditLogEntriesByTargetParams) ([]AuditLogEntry, error)
	ListConversationsByMerchant(ctx context.Context, arg ListConversationsByMerchantParams) ([]Conversation, error)
	ListDeliveryOptionsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]DeliveryOption, error)
	ListInvoiceLineItems(ctx context.Context, invoiceID pgtype.UUID) ([]InvoiceLineItem, error)
	ListInvoicesByMerchant(ctx context.Context, arg ListInvoicesByMerchantParams) ([]Invoice, error)
	ListItemsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Item, error)
	ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error)
	ListPaymentsByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]Payment, error)
	ListPendingOrderRequestsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]OrderRequest, error)
	ListSettlementsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Settlement, error)
	ListStaffByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Staff, error)
	SetDeliveryOptionStatus(ctx context.Context, arg SetDeliveryOptionStatusParams) error
	SetInvoiceStatus(ctx context.Context, arg SetInvoiceStatusParams) (Invoice, error)
	SetOrderRequestStatus(ctx context.Context, arg SetOrderRequestStatusParams) (OrderRequest, error)
	SetPaymentStatus(ctx context.Context, arg SetPaymentStatusParams) (Payment, error)
	SetSettlementStatus(ctx context.Context, arg SetSettlementStatusParams) (Settlement, error)
	SumSuccessfulPaymentsByInvoice(ctx context.Context, invoiceID pgtype.UUID) (int64, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
	UpdateMerchantFeeSettings(ctx context.Context, arg UpdateMerchantFeeSettingsParams) (Merchant, error)
	UpdateMerchantKYCTier(ctx context.Context, arg UpdateMerchantKYCTierParams) (Merchant, error)
	UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (Merchant, error)
	UpsertGlobalFeeRule(ctx context.Context, arg UpsertGlobalFeeRuleParams) (FeeRule, error)
	UpsertMerchantFeeRule(ctx context.Context, arg UpsertMerchantFeeRuleParams) (FeeRule, error)
}

var _ Querier = (*Queries)(nil)
