// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: reporting.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyRevenue = `-- name: GetDailyRevenue :many
SELECT
  DATE(p.paid_at) AS day,
  COALESCE(SUM(p.amount_pesewas), 0)::bigint AS gmv_pesewas,
  COALESCE(SUM(p.psp_fee_pesewas), 0)::bigint AS psp_fees_pesewas,
  COALESCE(SUM(i.commission_pesewas * p.amount_pesewas / NULLIF(i.total_pesewas, 0)), 0)::bigint AS commission_pesewas
FROM payments p
JOIN invoices i ON i.id = p.invoice_id
WHERE p.status = 'success'
  AND p.paid_at >= $1::timestamptz
  AND p.paid_at < $2::timestamptz
GROUP BY DATE(p.paid_at)
ORDER BY day
`

type GetDailyRevenueParams struct {
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type GetDailyRevenueRow struct {
	Day               pgtype.Date `json:"day"`
	GmvPesewas        int64       `json:"gmv_pesewas"`
	PspFeesPesewas    int64       `json:"psp_fees_pesewas"`
	CommissionPesewas int64       `json:"commission_pesewas"`
}

// Daily time series for the same period — only days with at least one
// successful payment (a table doesn't need zero-filled gap rows the way a
// chart would).
func (q *Queries) GetDailyRevenue(ctx context.Context, arg GetDailyRevenueParams) ([]GetDailyRevenueRow, error) {
	rows, err := q.db.Query(ctx, getDailyRevenue, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyRevenueRow{}
	for rows.Next() {
		var i GetDailyRevenueRow
		if err := rows.Scan(
			&i.Day,
			&i.GmvPesewas,
			&i.PspFeesPesewas,
			&i.CommissionPesewas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantRevenueBreakdown = `-- name: GetMerchantRevenueBreakdown :many
SELECT
  m.id AS merchant_id,
  m.business_name,
  m.status AS merchant_status,
  COALESCE(SUM(p.amount_pesewas), 0)::bigint AS gmv_pesewas,
  COALESCE(SUM(p.psp_fee_pesewas), 0)::bigint AS psp_fees_pesewas,
  COALESCE(SUM(i.commission_pesewas * p.amount_pesewas / NULLIF(i.total_pesewas, 0)), 0)::bigint AS commission_pesewas,
  COUNT(p.id)::bigint AS payment_count
FROM merchants m
LEFT JOIN invoices i ON i.merchant_id = m.id
LEFT JOIN payments p ON p.invoice_id = i.id
  AND p.status = 'success'
  AND p.paid_at >= $1::timestamptz
  AND p.paid_at < $2::timestamptz
GROUP BY m.id, m.business_name, m.status
ORDER BY gmv_pesewas DESC, m.business_name
`

type GetMerchantRevenueBreakdownParams struct {
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type GetMerchantRevenueBreakdownRow struct {
	MerchantID        pgtype.UUID `json:"merchant_id"`
	BusinessName      string      `json:"business_name"`
	MerchantStatus    string      `json:"merchant_status"`
	GmvPesewas        int64       `json:"gmv_pesewas"`
	PspFeesPesewas    int64       `json:"psp_fees_pesewas"`
	CommissionPesewas int64       `json:"commission_pesewas"`
	PaymentCount      int64       `json:"payment_count"`
}

// Section 7.5: one row per merchant for the selected period — LEFT JOINs
// so a merchant with zero activity in the period still appears (with all
// figures at 0), which is exactly what "active vs. dormant" needs to be
// computed from in Go rather than a second query. Commission is prorated
// by how much of each invoice was actually collected in the period, the
// same pattern as the settlement engine's ComputeSettlementAggregate.
func (q *Queries) GetMerchantRevenueBreakdown(ctx context.Context, arg GetMerchantRevenueBreakdownParams) ([]GetMerchantRevenueBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getMerchantRevenueBreakdown, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMerchantRevenueBreakdownRow{}
	for rows.Next() {
		var i GetMerchantRevenueBreakdownRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.BusinessName,
			&i.MerchantStatus,
			&i.GmvPesewas,
			&i.PspFeesPesewas,
			&i.CommissionPesewas,
			&i.PaymentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
