// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: risk.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRiskFlag = `-- name: CreateRiskFlag :exec
INSERT INTO risk_flags (merchant_id, flag_type, dedupe_key, details)
VALUES ($1, $2, $3, $4)
ON CONFLICT (merchant_id, flag_type, dedupe_key) WHERE status = 'open' DO NOTHING
`

type CreateRiskFlagParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	FlagType   string      `json:"flag_type"`
	DedupeKey  string      `json:"dedupe_key"`
	Details    string      `json:"details"`
}

// Silently skipped when an identical open flag already exists
// (risk_flags_dedupe_open) — a scan re-run should never spam duplicates.
func (q *Queries) CreateRiskFlag(ctx context.Context, arg CreateRiskFlagParams) error {
	_, err := q.db.Exec(ctx, createRiskFlag,
		arg.MerchantID,
		arg.FlagType,
		arg.DedupeKey,
		arg.Details,
	)
	return err
}

const findDuplicateGhanaCardFlags = `-- name: FindDuplicateGhanaCardFlags :many
SELECT
  s.merchant_id,
  s.ghana_card_number,
  string_agg(DISTINCT m2.business_name, ', ')::text AS other_merchants
FROM kyc_submissions s
JOIN kyc_submissions s2 ON s2.ghana_card_number = s.ghana_card_number AND s2.merchant_id != s.merchant_id
JOIN merchants m2 ON m2.id = s2.merchant_id
GROUP BY s.merchant_id, s.ghana_card_number
`

type FindDuplicateGhanaCardFlagsRow struct {
	MerchantID      pgtype.UUID `json:"merchant_id"`
	GhanaCardNumber string      `json:"ghana_card_number"`
	OtherMerchants  string      `json:"other_merchants"`
}

// One row per merchant that shares a Ghana Card number with at least one
// other merchant's KYC submission (any status — even a rejected submission
// reusing someone else's card number is a real signal).
func (q *Queries) FindDuplicateGhanaCardFlags(ctx context.Context) ([]FindDuplicateGhanaCardFlagsRow, error) {
	rows, err := q.db.Query(ctx, findDuplicateGhanaCardFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDuplicateGhanaCardFlagsRow{}
	for rows.Next() {
		var i FindDuplicateGhanaCardFlagsRow
		if err := rows.Scan(&i.MerchantID, &i.GhanaCardNumber, &i.OtherMerchants); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findVelocitySpikes = `-- name: FindVelocitySpikes :many
WITH today AS (
  SELECT merchant_id, COUNT(*) AS cnt, COALESCE(SUM(total_pesewas), 0)::bigint AS val
  FROM invoices
  WHERE created_at >= now() - interval '24 hours'
    AND status != 'draft'
  GROUP BY merchant_id
),
baseline AS (
  SELECT merchant_id,
    COUNT(*)::float8 / 7 AS avg_cnt,
    COALESCE(SUM(total_pesewas), 0)::float8 / 7 AS avg_val
  FROM invoices
  WHERE created_at >= now() - interval '8 days'
    AND created_at < now() - interval '24 hours'
    AND status != 'draft'
  GROUP BY merchant_id
)
SELECT
  t.merchant_id,
  t.cnt AS today_count,
  t.val AS today_value_pesewas,
  COALESCE(b.avg_cnt, 0)::float8 AS baseline_avg_count,
  COALESCE(b.avg_val, 0)::float8 AS baseline_avg_value_pesewas
FROM today t
LEFT JOIN baseline b ON b.merchant_id = t.merchant_id
WHERE
  (t.cnt >= 5 AND (COALESCE(b.avg_cnt, 0) = 0 OR t.cnt::float8 > b.avg_cnt * 3))
  OR
  (t.val >= 500000 AND (COALESCE(b.avg_val, 0) = 0 OR t.val::float8 > b.avg_val * 3))
`

type FindVelocitySpikesRow struct {
	MerchantID              pgtype.UUID `json:"merchant_id"`
	TodayCount              int64       `json:"today_count"`
	TodayValuePesewas       int64       `json:"today_value_pesewas"`
	BaselineAvgCount        float64     `json:"baseline_avg_count"`
	BaselineAvgValuePesewas float64     `json:"baseline_avg_value_pesewas"`
}

// Flags a merchant whose trailing-24h invoice count or value is both above
// a floor (so a brand-new merchant's first few invoices don't trip it) and
// a multiple of their own trailing 7-day daily average (so an
// already-high-volume merchant isn't flagged just for staying busy).
func (q *Queries) FindVelocitySpikes(ctx context.Context) ([]FindVelocitySpikesRow, error) {
	rows, err := q.db.Query(ctx, findVelocitySpikes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindVelocitySpikesRow{}
	for rows.Next() {
		var i FindVelocitySpikesRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.TodayCount,
			&i.TodayValuePesewas,
			&i.BaselineAvgCount,
			&i.BaselineAvgValuePesewas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRiskFlag = `-- name: GetRiskFlag :one
SELECT id, merchant_id, flag_type, dedupe_key, details, status, resolution_notes, reviewed_by, reviewed_at, created_at, updated_at FROM risk_flags WHERE id = $1
`

func (q *Queries) GetRiskFlag(ctx context.Context, id pgtype.UUID) (RiskFlag, error) {
	row := q.db.QueryRow(ctx, getRiskFlag, id)
	var i RiskFlag
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.FlagType,
		&i.DedupeKey,
		&i.Details,
		&i.Status,
		&i.ResolutionNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRiskFlagsAdmin = `-- name: ListRiskFlagsAdmin :many
SELECT r.id, r.merchant_id, r.flag_type, r.dedupe_key, r.details, r.status, r.resolution_notes, r.reviewed_by, r.reviewed_at, r.created_at, r.updated_at, m.business_name AS merchant_business_name
FROM risk_flags r
JOIN merchants m ON m.id = r.merchant_id
WHERE ($1::text = '' OR r.status = $1::text)
ORDER BY r.created_at DESC
LIMIT $3 OFFSET $2
`

type ListRiskFlagsAdminParams struct {
	StatusFilter string `json:"status_filter"`
	RowOffset    int32  `json:"row_offset"`
	RowLimit     int32  `json:"row_limit"`
}

type ListRiskFlagsAdminRow struct {
	ID                   pgtype.UUID        `json:"id"`
	MerchantID           pgtype.UUID        `json:"merchant_id"`
	FlagType             string             `json:"flag_type"`
	DedupeKey            string             `json:"dedupe_key"`
	Details              string             `json:"details"`
	Status               string             `json:"status"`
	ResolutionNotes      pgtype.Text        `json:"resolution_notes"`
	ReviewedBy           pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	MerchantBusinessName string             `json:"merchant_business_name"`
}

func (q *Queries) ListRiskFlagsAdmin(ctx context.Context, arg ListRiskFlagsAdminParams) ([]ListRiskFlagsAdminRow, error) {
	rows, err := q.db.Query(ctx, listRiskFlagsAdmin, arg.StatusFilter, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRiskFlagsAdminRow{}
	for rows.Next() {
		var i ListRiskFlagsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.FlagType,
			&i.DedupeKey,
			&i.Details,
			&i.Status,
			&i.ResolutionNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MerchantBusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskFlagsByMerchant = `-- name: ListRiskFlagsByMerchant :many
SELECT id, merchant_id, flag_type, dedupe_key, details, status, resolution_notes, reviewed_by, reviewed_at, created_at, updated_at FROM risk_flags WHERE merchant_id = $1 ORDER BY created_at DESC
`

// Backs the Section 7.1 merchant detail view's "flags" panel.
func (q *Queries) ListRiskFlagsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]RiskFlag, error) {
	rows, err := q.db.Query(ctx, listRiskFlagsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiskFlag{}
	for rows.Next() {
		var i RiskFlag
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.FlagType,
			&i.DedupeKey,
			&i.Details,
			&i.Status,
			&i.ResolutionNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveRiskFlag = `-- name: ResolveRiskFlag :one
UPDATE risk_flags
SET status = $1, resolution_notes = $2,
    reviewed_by = $3, reviewed_at = now()
WHERE id = $4
RETURNING id, merchant_id, flag_type, dedupe_key, details, status, resolution_notes, reviewed_by, reviewed_at, created_at, updated_at
`

type ResolveRiskFlagParams struct {
	Status          string      `json:"status"`
	ResolutionNotes pgtype.Text `json:"resolution_notes"`
	ReviewedBy      pgtype.UUID `json:"reviewed_by"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) ResolveRiskFlag(ctx context.Context, arg ResolveRiskFlagParams) (RiskFlag, error) {
	row := q.db.QueryRow(ctx, resolveRiskFlag,
		arg.Status,
		arg.ResolutionNotes,
		arg.ReviewedBy,
		arg.ID,
	)
	var i RiskFlag
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.FlagType,
		&i.DedupeKey,
		&i.Details,
		&i.Status,
		&i.ResolutionNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
