// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: settlements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSettlement = `-- name: CreateSettlement :one
INSERT INTO settlements (merchant_id, period_start, period_end, gross_collections_pesewas, psp_fees_pesewas, commission_pesewas, net_payout_pesewas)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, period_start, period_end, gross_collections_pesewas, psp_fees_pesewas, commission_pesewas, net_payout_pesewas, status, created_at, updated_at
`

type CreateSettlementParams struct {
	MerchantID              pgtype.UUID `json:"merchant_id"`
	PeriodStart             pgtype.Date `json:"period_start"`
	PeriodEnd               pgtype.Date `json:"period_end"`
	GrossCollectionsPesewas int64       `json:"gross_collections_pesewas"`
	PspFeesPesewas          int64       `json:"psp_fees_pesewas"`
	CommissionPesewas       int64       `json:"commission_pesewas"`
	NetPayoutPesewas        int64       `json:"net_payout_pesewas"`
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, createSettlement,
		arg.MerchantID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.GrossCollectionsPesewas,
		arg.PspFeesPesewas,
		arg.CommissionPesewas,
		arg.NetPayoutPesewas,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.GrossCollectionsPesewas,
		&i.PspFeesPesewas,
		&i.CommissionPesewas,
		&i.NetPayoutPesewas,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettlementsByMerchant = `-- name: ListSettlementsByMerchant :many
SELECT id, merchant_id, period_start, period_end, gross_collections_pesewas, psp_fees_pesewas, commission_pesewas, net_payout_pesewas, status, created_at, updated_at FROM settlements WHERE merchant_id = $1 ORDER BY period_start DESC
`

func (q *Queries) ListSettlementsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Settlement, error) {
	rows, err := q.db.Query(ctx, listSettlementsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Settlement{}
	for rows.Next() {
		var i Settlement
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.GrossCollectionsPesewas,
			&i.PspFeesPesewas,
			&i.CommissionPesewas,
			&i.NetPayoutPesewas,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSettlementStatus = `-- name: SetSettlementStatus :one
UPDATE settlements SET status = $2 WHERE id = $1
RETURNING id, merchant_id, period_start, period_end, gross_collections_pesewas, psp_fees_pesewas, commission_pesewas, net_payout_pesewas, status, created_at, updated_at
`

type SetSettlementStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetSettlementStatus(ctx context.Context, arg SetSettlementStatusParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, setSettlementStatus, arg.ID, arg.Status)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.GrossCollectionsPesewas,
		&i.PspFeesPesewas,
		&i.CommissionPesewas,
		&i.NetPayoutPesewas,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
