// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: staff.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStaff = `-- name: CreateStaff :one
INSERT INTO staff (merchant_id, name, phone, role)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, name, phone, role, created_at, updated_at
`

type CreateStaffParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Name       string      `json:"name"`
	Phone      string      `json:"phone"`
	Role       string      `json:"role"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.MerchantID,
		arg.Name,
		arg.Phone,
		arg.Role,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStaff = `-- name: DeleteStaff :exec
DELETE FROM staff WHERE id = $1
`

func (q *Queries) DeleteStaff(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStaff, id)
	return err
}

const getStaffByPhone = `-- name: GetStaffByPhone :one
SELECT id, merchant_id, name, phone, role, created_at, updated_at FROM staff WHERE phone = $1
`

func (q *Queries) GetStaffByPhone(ctx context.Context, phone string) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByPhone, phone)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaffByMerchant = `-- name: ListStaffByMerchant :many
SELECT id, merchant_id, name, phone, role, created_at, updated_at FROM staff WHERE merchant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStaffByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaffByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Staff{}
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Phone,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
