// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: staff.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStaff = `-- name: CreateStaff :one
INSERT INTO staff (merchant_id, name, phone, role, email, password_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, merchant_id, name, phone, role, created_at, updated_at, email, password_hash
`

type CreateStaffParams struct {
	MerchantID   pgtype.UUID `json:"merchant_id"`
	Name         string      `json:"name"`
	Phone        string      `json:"phone"`
	Role         string      `json:"role"`
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.MerchantID,
		arg.Name,
		arg.Phone,
		arg.Role,
		arg.Email,
		arg.PasswordHash,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const deleteStaff = `-- name: DeleteStaff :execrows
DELETE FROM staff WHERE id = $1 AND merchant_id = $2
`

type DeleteStaffParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

// merchant_id in the WHERE clause, not just id — a staff row belongs to
// exactly one merchant, and the caller must own it (RowsAffected() == 0
// means either it doesn't exist or belongs to someone else; either way
// the handler reports 404, not which).
func (q *Queries) DeleteStaff(ctx context.Context, arg DeleteStaffParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaff, arg.ID, arg.MerchantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStaffByEmail = `-- name: GetStaffByEmail :one
SELECT id, merchant_id, name, phone, role, created_at, updated_at, email, password_hash FROM staff WHERE email = $1::text
`

func (q *Queries) GetStaffByEmail(ctx context.Context, dollar_1 string) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByEmail, dollar_1)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getStaffByPhone = `-- name: GetStaffByPhone :one
SELECT id, merchant_id, name, phone, role, created_at, updated_at, email, password_hash FROM staff WHERE phone = $1
`

func (q *Queries) GetStaffByPhone(ctx context.Context, phone string) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByPhone, phone)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const listStaffByMerchant = `-- name: ListStaffByMerchant :many
SELECT id, merchant_id, name, phone, role, created_at, updated_at, email, password_hash FROM staff WHERE merchant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStaffByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaffByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Staff{}
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Phone,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
