// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: support.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSupportTransaction = `-- name: GetSupportTransaction :one
SELECT i.id, i.merchant_id, i.order_request_id, i.reference, i.customer_contact, i.subtotal_pesewas, i.service_charge_pesewas, i.service_charge_allocation, i.total_pesewas, i.status, i.delivery_option_id, i.delivery_address, i.delivery_fee_handling, i.delivery_fee_pesewas, i.expires_at, i.created_at, i.updated_at, i.commission_pesewas, m.business_name AS merchant_business_name, m.phone AS merchant_phone
FROM invoices i
JOIN merchants m ON m.id = i.merchant_id
WHERE i.reference = $1::text
`

type GetSupportTransactionRow struct {
	ID                      pgtype.UUID        `json:"id"`
	MerchantID              pgtype.UUID        `json:"merchant_id"`
	OrderRequestID          pgtype.UUID        `json:"order_request_id"`
	Reference               string             `json:"reference"`
	CustomerContact         string             `json:"customer_contact"`
	SubtotalPesewas         int64              `json:"subtotal_pesewas"`
	ServiceChargePesewas    int64              `json:"service_charge_pesewas"`
	ServiceChargeAllocation string             `json:"service_charge_allocation"`
	TotalPesewas            int64              `json:"total_pesewas"`
	Status                  string             `json:"status"`
	DeliveryOptionID        pgtype.UUID        `json:"delivery_option_id"`
	DeliveryAddress         pgtype.Text        `json:"delivery_address"`
	DeliveryFeeHandling     pgtype.Text        `json:"delivery_fee_handling"`
	DeliveryFeePesewas      pgtype.Int8        `json:"delivery_fee_pesewas"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	CommissionPesewas       int64              `json:"commission_pesewas"`
	MerchantBusinessName    string             `json:"merchant_business_name"`
	MerchantPhone           string             `json:"merchant_phone"`
}

func (q *Queries) GetSupportTransaction(ctx context.Context, reference string) (GetSupportTransactionRow, error) {
	row := q.db.QueryRow(ctx, getSupportTransaction, reference)
	var i GetSupportTransactionRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.OrderRequestID,
		&i.Reference,
		&i.CustomerContact,
		&i.SubtotalPesewas,
		&i.ServiceChargePesewas,
		&i.ServiceChargeAllocation,
		&i.TotalPesewas,
		&i.Status,
		&i.DeliveryOptionID,
		&i.DeliveryAddress,
		&i.DeliveryFeeHandling,
		&i.DeliveryFeePesewas,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionPesewas,
		&i.MerchantBusinessName,
		&i.MerchantPhone,
	)
	return i, err
}

const searchInvoicesForSupport = `-- name: SearchInvoicesForSupport :many
SELECT i.id, i.merchant_id, i.order_request_id, i.reference, i.customer_contact, i.subtotal_pesewas, i.service_charge_pesewas, i.service_charge_allocation, i.total_pesewas, i.status, i.delivery_option_id, i.delivery_address, i.delivery_fee_handling, i.delivery_fee_pesewas, i.expires_at, i.created_at, i.updated_at, i.commission_pesewas, m.business_name AS merchant_business_name, m.phone AS merchant_phone
FROM invoices i
JOIN merchants m ON m.id = i.merchant_id
WHERE i.status != 'draft'
  AND (i.reference ILIKE '%' || $1::text || '%'
       OR i.customer_contact ILIKE '%' || $1::text || '%')
ORDER BY i.created_at DESC
LIMIT 25
`

type SearchInvoicesForSupportRow struct {
	ID                      pgtype.UUID        `json:"id"`
	MerchantID              pgtype.UUID        `json:"merchant_id"`
	OrderRequestID          pgtype.UUID        `json:"order_request_id"`
	Reference               string             `json:"reference"`
	CustomerContact         string             `json:"customer_contact"`
	SubtotalPesewas         int64              `json:"subtotal_pesewas"`
	ServiceChargePesewas    int64              `json:"service_charge_pesewas"`
	ServiceChargeAllocation string             `json:"service_charge_allocation"`
	TotalPesewas            int64              `json:"total_pesewas"`
	Status                  string             `json:"status"`
	DeliveryOptionID        pgtype.UUID        `json:"delivery_option_id"`
	DeliveryAddress         pgtype.Text        `json:"delivery_address"`
	DeliveryFeeHandling     pgtype.Text        `json:"delivery_fee_handling"`
	DeliveryFeePesewas      pgtype.Int8        `json:"delivery_fee_pesewas"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	CommissionPesewas       int64              `json:"commission_pesewas"`
	MerchantBusinessName    string             `json:"merchant_business_name"`
	MerchantPhone           string             `json:"merchant_phone"`
}

// Matches on invoice reference or customer phone — the two things a support
// agent is handed on a call ("my order is ORD-1234" / "I paid with 024...").
func (q *Queries) SearchInvoicesForSupport(ctx context.Context, query string) ([]SearchInvoicesForSupportRow, error) {
	rows, err := q.db.Query(ctx, searchInvoicesForSupport, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchInvoicesForSupportRow{}
	for rows.Next() {
		var i SearchInvoicesForSupportRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.OrderRequestID,
			&i.Reference,
			&i.CustomerContact,
			&i.SubtotalPesewas,
			&i.ServiceChargePesewas,
			&i.ServiceChargeAllocation,
			&i.TotalPesewas,
			&i.Status,
			&i.DeliveryOptionID,
			&i.DeliveryAddress,
			&i.DeliveryFeeHandling,
			&i.DeliveryFeePesewas,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommissionPesewas,
			&i.MerchantBusinessName,
			&i.MerchantPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMerchantsForSupport = `-- name: SearchMerchantsForSupport :many
SELECT id, business_name, category, phone, kyc_tier, status, service_charge_allocation, service_charge_split_bps, payout_account_type, payout_account_ref, payout_schedule, payout_min_threshold_pesewas, created_at, updated_at, payout_fee_absorption FROM merchants
WHERE business_name ILIKE '%' || $1::text || '%'
   OR phone ILIKE '%' || $1::text || '%'
ORDER BY created_at DESC
LIMIT 25
`

func (q *Queries) SearchMerchantsForSupport(ctx context.Context, query string) ([]Merchant, error) {
	rows, err := q.db.Query(ctx, searchMerchantsForSupport, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Merchant{}
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.BusinessName,
			&i.Category,
			&i.Phone,
			&i.KycTier,
			&i.Status,
			&i.ServiceChargeAllocation,
			&i.ServiceChargeSplitBps,
			&i.PayoutAccountType,
			&i.PayoutAccountRef,
			&i.PayoutSchedule,
			&i.PayoutMinThresholdPesewas,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PayoutFeeAbsorption,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
