// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserPermissionKeys = `-- name: GetUserPermissionKeys :many
SELECT DISTINCT p.key FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = $1
UNION
SELECT DISTINCT p.key FROM permissions p
JOIN user_permissions up ON up.permission_id = p.id
WHERE up.user_id = $1
`

// GetUserPermissionKeys is the union of permissions granted via the user's
// roles and any direct per-user grants — this is what gets embedded in the
// PASETO token payload at login time.
func (q *Queries) GetUserPermissionKeys(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissionKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantUserPermission = `-- name: GrantUserPermission :exec
INSERT INTO user_permissions (user_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type GrantUserPermissionParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) GrantUserPermission(ctx context.Context, arg GrantUserPermissionParams) error {
	_, err := q.db.Exec(ctx, grantUserPermission, arg.UserID, arg.PermissionID)
	return err
}

const listUserDirectPermissions = `-- name: ListUserDirectPermissions :many
SELECT p.id, p.permission_group_id, p.key, p.name, p.description, p.created_at, p.updated_at FROM permissions p
JOIN user_permissions up ON up.permission_id = p.id
WHERE up.user_id = $1
ORDER BY p.key
`

func (q *Queries) ListUserDirectPermissions(ctx context.Context, userID pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listUserDirectPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.PermissionGroupID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserPermission = `-- name: RevokeUserPermission :exec
DELETE FROM user_permissions WHERE user_id = $1 AND permission_id = $2
`

type RevokeUserPermissionParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) RevokeUserPermission(ctx context.Context, arg RevokeUserPermissionParams) error {
	_, err := q.db.Exec(ctx, revokeUserPermission, arg.UserID, arg.PermissionID)
	return err
}
