// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: webhook_deliveries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :exec
INSERT INTO webhook_deliveries (provider, event_type, reference, signature_valid, processed_ok, error_message)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWebhookDeliveryParams struct {
	Provider       string      `json:"provider"`
	EventType      pgtype.Text `json:"event_type"`
	Reference      pgtype.Text `json:"reference"`
	SignatureValid bool        `json:"signature_valid"`
	ProcessedOk    bool        `json:"processed_ok"`
	ErrorMessage   pgtype.Text `json:"error_message"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, createWebhookDelivery,
		arg.Provider,
		arg.EventType,
		arg.Reference,
		arg.SignatureValid,
		arg.ProcessedOk,
		arg.ErrorMessage,
	)
	return err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, provider, event_type, reference, signature_valid, processed_ok, error_message, received_at FROM webhook_deliveries ORDER BY received_at DESC LIMIT $1 OFFSET $2
`

type ListWebhookDeliveriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.EventType,
			&i.Reference,
			&i.SignatureValid,
			&i.ProcessedOk,
			&i.ErrorMessage,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
